### ISSUE TITLE
Text control for in-place editing too small in wxTreeCtrl with wxGTK

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#23001] opened 2022-11-28 13:17 UTC
### Description

The text control that appears in a `wxTreeCtrl` for in-place editing of an item label is a bit too small with wxGTK.

The issue can be seen in the treectrl sample.

With wxMSW, the text control is large enough to contain the entire item text.
![wxTreeCtrl_MSW](https://user-images.githubusercontent.com/99262969/204286543-36030a29-6ee1-4a06-a1f3-b462ae1badee.png)

With wxGTK (using **GTK2**), the text control is a bit too small.
![wxTreeCtrl_GTK2](https://user-images.githubusercontent.com/99262969/204286653-ea09a4d9-fd45-4aba-b5cb-9644e5549974.png)

With wxGTK (using **GTK3**), the text control is about one character too small.
![wxTreeCtrl_GTK3](https://user-images.githubusercontent.com/99262969/204286691-91c972b8-aca8-42eb-9cee-78dba8a60d24.png)

### Platform and version information

- wxWidgets version  you use: 3.2.0
- wxWidgets port  you use: wxGTK
- OS  and its version: Linux Mint 19, Ubuntu 22.04

+ GTK version: 2.24 and 3.22
+ Which GDK  backend is used: X11
+ Current theme:

**Comment by vadz** [comment] 2022-11-28 13:22
This should be simple enough to fix as this code in `wxTreeTextCtrl` ctor

https://github.com/wxWidgets/wxWidgets/blob/58f5a885ec20ea518f94e16d2fcff6d0b8decd17/src/generic/treectlg.cpp#L434-L443

uses hard-coded values when it should at least be using something font-based and probably should really use `wxControl::GetSizeFromText()` instead. If you could please try changing this and submitting a PR with the changes if they work, it would be most welcome!

**Comment by taler21** [comment] 2022-11-29 11:21
Unfortunately it is not that simple.

* Is there a way to get the size of the empty space between the control border and the text?
  `GetMargins()` cannot be used, it returns `-1`.

* How can this `wxTreeTextCtrl` implementation also be tested under MSW?
  By default, this code is not effective there.

I noticed that the automatic enlargement of the text control when entering a text is also too small.

If no one has a better solution, I suggest the following changes as an improvement:

```patch
diff --git "a/src/generic/treectlg.cpp" "b/src/generic/treectlg.cpp"
index 0507194416..cd08270579 100644
--- "a/src/generic/treectlg.cpp"
+++ "b/src/generic/treectlg.cpp"
@@ -443,6 +443,15 @@ wxTreeTextCtrl::wxTreeTextCtrl(wxGenericTreeCtrl *owner,
     (void)Create(m_owner, wxID_ANY, m_startValue,
                  rect.GetPosition(), rect.GetSize());
 
+    // correct size to fit the text length
+    wxSize parentSize = m_owner->GetSize();
+    int sx, sy;
+    GetTextExtent(GetValue() + wxT("MM"), &sx, &sy);
+    rect.width  = wxMax( rect.width, sx );
+    if (rect.x + rect.width > parentSize.x)
+        rect.width = parentSize.x - rect.x;
+    SetInitialSize( rect.GetSize() );
+
     SelectAll();
 }
 
@@ -544,7 +553,7 @@ void wxTreeTextCtrl::OnKeyUp( wxKeyEvent &event )
         wxPoint myPos = GetPosition();
         wxSize mySize = GetSize();
         int sx, sy;
-        GetTextExtent(GetValue() + wxT("M"), &sx, &sy);
+        GetTextExtent(GetValue() + wxT("MM"), &sx, &sy);
         if (myPos.x + sx > parentSize.x)
             sx = parentSize.x - myPos.x;
         if (mySize.x > sx)

```

Resulting in the following appearance.

With wxGTK (using **GTK2**):
![wxTreeCtrl_GTK2_improved](https://user-images.githubusercontent.com/99262969/204515790-7f5e0280-9137-41e0-af93-ac6ddc64b59e.png)

With wxGTK (using **GTK3**):
![wxTreeCtrl_GTK3_improved](https://user-images.githubusercontent.com/99262969/204515823-5542c0c1-d1c0-45ed-8d78-5bf24c265af2.png)

**Comment by taler21** [comment] 2022-12-02 13:39
I think I have now what you want. (The patch is for 3.2 branch.)

```patch
diff --git "a/src/generic/treectlg.cpp" "b/src/generic/treectlg.cpp"
index 0507194416..57f8cc3567 100644
--- "a/src/generic/treectlg.cpp"
+++ "b/src/generic/treectlg.cpp"
@@ -98,9 +98,10 @@ public:
 
 protected:
     void OnChar( wxKeyEvent &event );
-    void OnKeyUp( wxKeyEvent &event );
     void OnKillFocus( wxFocusEvent &event );
 
+    void IncreaseSizeForText( const wxString& text );
+
     bool AcceptChanges();
     void Finish( bool setfocus );
 
@@ -415,7 +416,6 @@ void wxTreeRenameTimer::Notify()
 
 wxBEGIN_EVENT_TABLE(wxTreeTextCtrl,wxTextCtrl)
     EVT_CHAR           (wxTreeTextCtrl::OnChar)
-    EVT_KEY_UP         (wxTreeTextCtrl::OnKeyUp)
     EVT_KILL_FOCUS     (wxTreeTextCtrl::OnKillFocus)
 wxEND_EVENT_TABLE()
 
@@ -432,17 +432,17 @@ wxTreeTextCtrl::wxTreeTextCtrl(wxGenericTreeCtrl *owner,
     // corrects position and size for better appearance
 #ifdef __WXMSW__
     rect.x -= 5;
-    rect.width += 10;
 #elif defined(__WXGTK__)
     rect.x -= 5;
     rect.y -= 2;
-    rect.width  += 8;
     rect.height += 4;
 #endif // platforms
 
     (void)Create(m_owner, wxID_ANY, m_startValue,
                  rect.GetPosition(), rect.GetSize());
 
+    IncreaseSizeForText( GetValue() );
+
     SelectAll();
 }
 
@@ -531,11 +531,30 @@ void wxTreeTextCtrl::OnChar( wxKeyEvent &event )
             break;
 
         default:
+#if wxUSE_UNICODE
+            wxChar ch = event.GetUnicodeKey();
+#else // !wxUSE_UNICODE
+            wxChar ch = wxIsprint(event.GetKeyCode()) ? (wxChar)event.GetKeyCode()
+                                                      : WXK_NONE;
+#endif // wxUSE_UNICODE/!wxUSE_UNICODE
+            if ( ch != WXK_NONE )
+            {
+                wxString value = GetValue();
+
+                long from, to;
+                GetSelection( &from, &to );
+                if ( from != to )
+                {
+                    value.Remove( from, to - from );
+                }
+
+                IncreaseSizeForText( value + ch );
+            }
             event.Skip();
     }
 }
 
-void wxTreeTextCtrl::OnKeyUp( wxKeyEvent &event )
+void wxTreeTextCtrl::IncreaseSizeForText( const wxString& text )
 {
     if ( !m_aboutToFinish )
     {
@@ -543,16 +562,13 @@ void wxTreeTextCtrl::OnKeyUp( wxKeyEvent &event )
         wxSize parentSize = m_owner->GetSize();
         wxPoint myPos = GetPosition();
         wxSize mySize = GetSize();
-        int sx, sy;
-        GetTextExtent(GetValue() + wxT("M"), &sx, &sy);
+        int sx = GetSizeFromText( text ).GetWidth();
         if (myPos.x + sx > parentSize.x)
             sx = parentSize.x - myPos.x;
         if (mySize.x > sx)
             sx = mySize.x;
         SetSize(sx, wxDefaultCoord);
     }
-
-    event.Skip();
 }
 
 void wxTreeTextCtrl::OnKillFocus( wxFocusEvent &event )

```

I changed the following:
- For setting the width `GetSizeFromText()` is now used instead of `GetTextExtent()` and some hardcoded values or characters.
- The size will be increased on key down instead of key up.
  This leads to a much better behavior and corresponds to what the native control does on Windows.
  Just press and hold a button and you'll see the difference.

I have tested it on:
- Windows 7 and Windows 10
- openSUSE Leap 42.3 with KDE desktop
- Ubuntu 22.04 with GNOME desktop
- Linux Mint 21.3 with Cinnamon desktop

In principle it works fine.

I only noticed one strange behavior with GTK2 under Linux Mint.
There `GetSizeFromText()` returns a size that is to small, when a character is entered at the end of the text.
For example, if the character `A` is entered before the last existing character, the size increases by 9 pixels, but if the character is entered at the end the size only increases by 5 pixels.

**Comment by taler21** [comment] 2022-12-05 15:01
> I only noticed one strange behavior with GTK2 under Linux Mint.

I investigated this further.

On Linux Mint in `wxControl::GTKGetEntryMargins` the inner border cannot be determined.
https://github.com/wxWidgets/wxWidgets/blob/0f54ec8b36cd3551d7a3ee9593994adebb14cfa3/src/gtk/control.cpp#L378-L397

On openSUSE and Ubuntu a `innerBorder2` of 7 pixels is determined for each horizontal side.

In the meantime I have also tested it with Linux Mint 20 and it is the same problem there as with Linux Mint 19.

Could this be a problem with the GTK2 version 2.24.32?
```
openSUSE 42.3 - 2.24.31
Linux Mint 19 - 2.24.32
Linux Mint 20 - 2.24.32
Ubuntu 22.04  - 2.24.33
```

**Comment by vadz** [comment] 2022-12-05 19:26
I think it's due to a style not defining this border being used rather than GTK version. But it doesn't really help as I don't know what else can we do about it. What are the actual borders used under Mint?

**Comment by taler21** [comment] 2022-12-06 08:36
You are right, it is a theme specific issue.

With theme 'Adwaita' it works correct and a `innerBorder2` of 7 pixels is determined.
But with all the Mint themes (default is 'Mint-Y') the inner border cannot be determined.

The inner border must be at least 4 pixels on each horizontal side to make it work correctly.
I tested it on Linux Mint 19, 20 and 21.

```patch
diff --git "a/src/gtk/control.cpp" "b/src/gtk/control.cpp"
index f4a25ea146..33f769af0e 100644
--- "a/src/gtk/control.cpp"
+++ "b/src/gtk/control.cpp"
@@ -392,6 +392,12 @@ wxSize wxControl::GTKGetEntryMargins(GtkEntry* entry) const
                 border = *innerBorder2;
                 gtk_border_free(innerBorder2);
             }
+            else
+            {
+                // With Mint themes, the inner borders cannot be determined,
+                // but at least 4 pixels must be assumed.
+                border.left = border.right = 4;
+            }
         }
     }
 #endif // GTK+ 2.10+

```
![treeTextCtrl_4px](https://user-images.githubusercontent.com/99262969/205860475-ff4cb04c-c494-438c-b3fd-eac020f0f5e3.png)

But it is probably not harmful if 7 pixels are used as default, is it?
![treeTextCtrl_7px](https://user-images.githubusercontent.com/99262969/205860571-4b4d18b8-856b-4ff1-852a-631f90368c46.png)

**Comment by taler21** [comment] 2022-12-15 09:06
Yes, with this change, the text control is large enough.

So if this change is applied, the change I suggested [in this previous comment](https://github.com/wxWidgets/wxWidgets/issues/23001#issuecomment-1335247566) works perfectly fine.

With wxGTK (using **GTK2**) and both patches:
![wxTreeCtrl_GTK2_improved-3](https://user-images.githubusercontent.com/99262969/207817560-17bde67a-2e32-4b99-9dcd-75f15042ebe5.png)

**Comment by vadz** [comment] 2023-01-13 18:32
Sorry, I'm a bit lost about what has happened here: on one hand, b57ae63acf (Use GetSizeFromTextSize() to set initial size of in-place edit control, 2022-12-08) was done by Paul which conflicts with the changes "in this previous comment" but doesn't replace all of them, notably it doesn't touch `OnKeyUp()`. FWIW I don't think it's we should do what the code does in `OnChar()`, but rather in `OnKeyDown()`, and I think we might want to keep the test for `m_aboutToFinish`, but I agree that it would be better to do this on key press and not release and it's definitely better to use `GetSizeFromText()` instead of `GetTextExtent()`. Should this still be applied?

Also, the patch from Paul's own comment above with the GTK2 fix was not committed neither, should I push it too or was there any reason for not doing this?

I'd like to fix this in master and backport it to 3.2 as it seems a pity to leave this unfinished when the work has been already (mostly) done.

**Comment by paulcor** [comment] 2023-01-13 19:10
I don't think my patch above is correct. It's difficult to figure out what GTK is doing, and I ran out of motivation for spending a lot of time on GTK2. Additionally, the generic `wxTreeCtrl` is riddled with unexplained offsets, some of which appear to cancel each other out. In order to really understand what is going on, all that needs to be cleaned up as well.

**Comment by vadz** [comment] 2023-01-14 13:23
I'm not very motivated to spend time on GTK2 neither, but the OP wrote that with your changes using `GetSizeFromTextSize()` worked correctly for them, so it looks like it improves things...

**Comment by taler21** [comment] 2023-01-16 08:46
> Sorry, I'm a bit lost about what has happened here: on one hand, [b57ae63](https://github.com/wxWidgets/wxWidgets/commit/b57ae63acf0476f0196cb95cd46964960461f852) (Use GetSizeFromTextSize() to set initial size of in-place edit control, 2022-12-08) was done by Paul which conflicts with the changes "in this previous comment"

My proposed changes should be preferred to that applied in [b57ae63](https://github.com/wxWidgets/wxWidgets/commit/b57ae63acf0476f0196cb95cd46964960461f852), because they limit the length of the text control when necessary, so that it is not truncated if the text is longer than the space available in the tree.

> I don't think we should do what the code does in `OnChar()`, but rather in `OnKeyDown()`, and I think we might want to keep the test for `m_aboutToFinish`

Here is the adjusted patch (for 3.2 branch):

```patch
diff --git "a/src/generic/treectlg.cpp" "b/src/generic/treectlg.cpp"
index 0507194416..1752e425a5 100644
--- "a/src/generic/treectlg.cpp"
+++ "b/src/generic/treectlg.cpp"
@@ -97,10 +97,12 @@ public:
     const wxGenericTreeItem* item() const { return m_itemEdited; }
 
 protected:
+    void OnKeyDown( wxKeyEvent &event );
     void OnChar( wxKeyEvent &event );
-    void OnKeyUp( wxKeyEvent &event );
     void OnKillFocus( wxFocusEvent &event );
 
+    void IncreaseWidthForText( const wxString& text );
+
     bool AcceptChanges();
     void Finish( bool setfocus );
 
@@ -414,8 +416,8 @@ void wxTreeRenameTimer::Notify()
 //-----------------------------------------------------------------------------
 
 wxBEGIN_EVENT_TABLE(wxTreeTextCtrl,wxTextCtrl)
+    EVT_KEY_DOWN       (wxTreeTextCtrl::OnKeyDown)
     EVT_CHAR           (wxTreeTextCtrl::OnChar)
-    EVT_KEY_UP         (wxTreeTextCtrl::OnKeyUp)
     EVT_KILL_FOCUS     (wxTreeTextCtrl::OnKillFocus)
 wxEND_EVENT_TABLE()
 
@@ -432,17 +434,17 @@ wxTreeTextCtrl::wxTreeTextCtrl(wxGenericTreeCtrl *owner,
     // corrects position and size for better appearance
 #ifdef __WXMSW__
     rect.x -= 5;
-    rect.width += 10;
 #elif defined(__WXGTK__)
     rect.x -= 5;
     rect.y -= 2;
-    rect.width  += 8;
     rect.height += 4;
 #endif // platforms
 
     (void)Create(m_owner, wxID_ANY, m_startValue,
                  rect.GetPosition(), rect.GetSize());
 
+    IncreaseWidthForText( GetValue() );
+
     SelectAll();
 }
 
@@ -518,6 +520,34 @@ void wxTreeTextCtrl::Finish( bool setfocus )
         m_owner->SetFocus();
 }
 
+void wxTreeTextCtrl::OnKeyDown( wxKeyEvent &event )
+{
+    if ( !m_aboutToFinish )
+    {
+#if wxUSE_UNICODE
+        wxChar ch = event.GetUnicodeKey();
+#else // !wxUSE_UNICODE
+        wxChar ch = wxIsprint(event.GetKeyCode()) ? (wxChar)event.GetKeyCode()
+                                                    : WXK_NONE;
+#endif // wxUSE_UNICODE/!wxUSE_UNICODE
+        if ( ch != WXK_NONE )
+        {
+            wxString value = GetValue();
+
+            long from, to;
+            GetSelection( &from, &to );
+            if ( from != to )
+            {
+                value.Remove( from, to - from );
+            }
+
+            IncreaseWidthForText( value + ch );
+        }
+    }
+
+    event.Skip();
+}
+
 void wxTreeTextCtrl::OnChar( wxKeyEvent &event )
 {
     switch ( event.m_keyCode )
@@ -535,24 +565,18 @@ void wxTreeTextCtrl::OnChar( wxKeyEvent &event )
     }
 }
 
-void wxTreeTextCtrl::OnKeyUp( wxKeyEvent &event )
+void wxTreeTextCtrl::IncreaseWidthForText( const wxString& text )
 {
-    if ( !m_aboutToFinish )
-    {
-        // auto-grow the textctrl:
-        wxSize parentSize = m_owner->GetSize();
-        wxPoint myPos = GetPosition();
-        wxSize mySize = GetSize();
-        int sx, sy;
-        GetTextExtent(GetValue() + wxT("M"), &sx, &sy);
-        if (myPos.x + sx > parentSize.x)
-            sx = parentSize.x - myPos.x;
-        if (mySize.x > sx)
-            sx = mySize.x;
-        SetSize(sx, wxDefaultCoord);
-    }
-
-    event.Skip();
+    // auto-grow the textctrl:
+    wxSize parentSize = m_owner->GetSize();
+    wxPoint myPos = GetPosition();
+    wxSize mySize = GetSize();
+    int sx = GetSizeFromText( text ).GetWidth();
+    if (myPos.x + sx > parentSize.x)
+        sx = parentSize.x - myPos.x;
+    if (mySize.x > sx)
+        sx = mySize.x;
+    SetSize(sx, wxDefaultCoord);
 }
 
 void wxTreeTextCtrl::OnKillFocus( wxFocusEvent &event )

```

My patch is an improvement, with and without [these changes](https://github.com/wxWidgets/wxWidgets/issues/23001#issuecomment-1339749792).
But with these changes, the text control is large enough even on Linux Mint and its specific styles.

**Comment by taler21** [comment] 2023-01-17 05:53
> I don't think we should do what the code does in `OnChar()`, but rather in `OnKeyDown()`

Thiking longer about it, I have to disagree here.

The entered character must be added to the text for calculating the required size, because the text does not contain the character at this point.
Therefor `OnChar()` has to be used, not `OnKeyDown()`. Because if you press the `M` key without `Shift` the character `m` has to be added, not `M`.

So I think my [previous patch](https://github.com/wxWidgets/wxWidgets/issues/23001#issuecomment-1335247566) is the right thing to do.

Maybe you want remove the check for `m_aboutToFinish` in `wxTreeTextCtrl::IncreaseSizeForText`, or move it to `wxTreeTextCtrl::OnChar`.
But the rest should be done basically as in this patch.

**Comment by vadz** [comment] 2023-01-31 23:45
OK, thanks, I agree with your latest comment, so I've created the PR referenced above with your patch. If there are no objections, I'll merge it soon and backport to 3.2 with the extra `wxUSE_UNICODE` test that I removed from the master version.

**Comment by vadz** [comment] 2023-02-01 19:10
Thanks for retesting!

For the extra height, do you mean just adding 4px? If so, we should do this inside `GetSizeFromText()`.

As for `GetSizeFromText()` doesn't work from `wxEVT_TEXT` handler, I have no idea, but we really shouldn't break GTK 3 behaviour, so for now let's leave it like this. It can/should be always improved more in the future, of course, but for now I'd like to get this fix in 3.2.2.

**Comment by taler21** [comment] 2023-02-02 07:32
I mean this. It's not just the height, it's also the offset in position.
```patch
diff --git "a/src/generic/treectlg.cpp" "b/src/generic/treectlg.cpp"
index a329290b68..aa3cf5f5f4 100644
--- "a/src/generic/treectlg.cpp"
+++ "b/src/generic/treectlg.cpp"
@@ -436,6 +436,8 @@ wxTreeTextCtrl::wxTreeTextCtrl(wxGenericTreeCtrl *owner,
     rect.x -= 5;
 #elif defined(__WXGTK__)
     rect.x -= 5;
+    rect.y -= 2;
+    rect.height += 4;
 #endif // platforms
 
     (void)Create(m_owner, wxID_ANY, m_startValue,

```

> As for `GetSizeFromText()` doesn't work from `wxEVT_TEXT` handler, I have no idea, but we really shouldn't break GTK 3 behaviour, so for now let's leave it like this. It can/should be always improved more in the future, of course, but for now I'd like to get this fix in 3.2.2.

Maybe @paulcor has an idea again?

**Comment by vadz** [comment] 2023-02-02 16:14
How about the new version of #23205? It looks better for me like this without hardcoding all these 2 and 4.

Thanks again for testing!

**Comment by taler21** [comment] 2023-02-03 07:03
I understand that you want to get rid of hardcoded numbers, but unfortunately in most cases it is worse now.
![wxTreeTextCtrl_without-hardcoded-extra-height](https://user-images.githubusercontent.com/99262969/216533634-07198554-86f9-400b-9f3c-ac14354cb2b0.png)

A second issue is that the width of the text control is not limited by the width of the tree.
So if the text is longer than the space available in the tree, starting rename now creates a text control that is too wide and therefore truncated.
Previously this case was taken into account in the called `IncreaseSizeForText()` method.

**Comment by vadz** [comment] 2023-02-03 14:17
Oops, sorry, I tested only with GTK 3 -- and I think it's mostly fine there now (the margins are a bit too big for my taste under Mint, but it's probably acceptable). But I need to fix this for GTK 2 and MSW now, of course.

**Comment by vadz** [comment] 2023-02-03 17:37
I've fixed the MSW problem (which was the same bug I'd fixed in wxGTK) and also the "second issue", but I can't reproduce the problem with huge margins with GTK 2 under Debian nor in my Ubuntu 22.04 chroot, but I must be missing some packages there as I don't have the orange-tinted Ubuntu theme at all.

Can we restore the hardcoded margins for GTK 2 only at least? I.e. would something like this:
```diff
diff --git a/src/gtk/textctrl.cpp b/src/gtk/textctrl.cpp
index 861645ae8f..e2bee66371 100644
--- a/src/gtk/textctrl.cpp
+++ b/src/gtk/textctrl.cpp
@@ -2150,8 +2150,12 @@ wxSize wxTextCtrl::DoGetSizeFromTextSize(int xlen, int ylen) const
         {
             // default height
             tsize.y = GTKGetPreferredSize(m_widget).y;
+#ifdef __WXGTK3__
             // Add the margins we have previously set.
             tsize.IncBy( GTKGetEntryMargins(GetEntry()) );
+#else
+            tsize.IncBy(4, 0);
+#endif
         }
     }

```
work?

**Comment by taler21** [comment] 2023-02-06 08:33
If your patch is used, the height is okay, but the textbox is too short.
![treectrl_gtk2_4px](https://user-images.githubusercontent.com/99262969/216922943-3601649f-e474-48dd-814b-91223c2af66b.png)

A hardcoded value of 16 is required so that the entire text is visible.
![treectrl_gtk2_16px](https://user-images.githubusercontent.com/99262969/216922970-e0363578-48d0-4b65-8e4a-d2e0ca3cde42.png)

**Comment by vadz** [comment] 2023-02-06 18:49
Thanks for your testing, I've finally installed Ubuntu 22.04 here, so I could also test it myself and it seems that 16 is still too small because the text visibly shifts after showing the control -- but 20 is enough without being too huge, so I've used this instead. This is clearly not ideal, but better than nothing and we can always improve this later.

If you don't see something very wrong with the latest master (i.e. making it _worse_ than before), then I'm also going to apply this to 3.2 soon.

Thanks again!

**Closed** 2023-02-06 18:49 UTC
Labels: GTK

**Comment by taler21** [comment] 2023-02-07 06:29
I think it's an improvement that should be applied to 3.2 as well. Thanks!

There is still the issue that when pasting from the clipboard, the size of the text control is not adjusted.
See the second point in that [previous comment](https://github.com/wxWidgets/wxWidgets/issues/23001#issuecomment-1411971012).
But that wasn't handled correctly before either. As you said, further improvements can always be made later.
