### ISSUE TITLE
Error in documentation of wxString::length() and all the other STL-compatible functions

### ISSUE THREAD

**Issue by wh11204** [wxWidgets/wxWidgets#22248] opened 2022-03-30 08:04 UTC
Description says "An 'invalid' value for string index. "

**Comment by PBfordev** [comment] 2022-03-30 08:34
Actually, much more is broken in `wxString` documentation in the trunk (it is OK in 3.1.5). I am not sure if this is related to recent  doxygen upgrades or changes in the `wxString` documentation.

Firstly, `npos` should not be in the _STL Functions_ but in _Static Public Attributes_ section

Secondly, all [_STL Functions_](https://docs.wxwidgets.org/trunk/classwx_string.html#stl) have the same incorrect descriptions (from `npos`, they have [none in 3.1.5](https://docs.wxwidgets.org/3.1.5/classwx_string.html#stl)).

Thirdly, the heading for _Static Public Functions_ is missing and the static methods are merged into  _STL Functions_. Moreover, if there is an overload for a static method, it also has the incorrect description.

**Comment by PBfordev** [comment] 2022-03-30 15:40
I can confirm that it must be doxygen version. I have generated HTML docs with doxygen 1.8.18 (on MSW), it is broken both in the master and 3.1.5.

There is already this before `npos`, but it seems that it is not sufficient any more:
https://github.com/wxWidgets/wxWidgets/blob/c63de862c43da2b3c3ee03d6a0bba9e45ba61faf/interface/wx/string.h#L1776-L1783

BTW, I still experience the issue with search results display:
1. There is a huge gap before the result list for the trunk: https://docs.wxwidgets.org/trunk/search.php?query=wxstring
2. There are no results and the top right display is broken for 3.1.5: https://docs.wxwidgets.org/3.1.5/search.php?query=wxstring

I am reasonably sure it is not due to my local browser cache (tried <Ctrl+F5> and browsers I normally do not use)

**Comment by vadz** [comment] 2022-03-30 15:51
> I can confirm that it must be doxygen version. I have generated HTML docs with doxygen 1.8.18 (on MSW), it is broken both in the master and 3.1.5.
> 
> There is already this before `npos`, but it seems that it is not sufficient any more:
> 
> https://github.com/wxWidgets/wxWidgets/blob/c63de862c43da2b3c3ee03d6a0bba9e45ba61faf/interface/wx/string.h#L1776-L1783

Maybe we need to put them in a group of their own?
 
> BTW, I still experience the issue with search results display:
> 
>     1. There is a huge gap before the result list for the trunk: https://docs.wxwidgets.org/trunk/search.php?query=wxstring

This is due to a bug which I just fixed in c63de862c43da2b3c3ee03d6a0bba9e45ba61faf (trunk docs still contained the old files because the new ones were not copied to the correct location). I've just updated the docs manually and purged Cloudflare cache again, so it should work correctly now if you _also_ purge your local cache once again.

>     2. There are no results and the top right display is broken for 3.1.5: https://docs.wxwidgets.org/3.1.5/search.php?query=wxstring

I'm afraid we'll just have to live with the search being broken for all the versions except for the latest one because the only solution I see is to update Doxyfile and rebuild them all with a more recent doxygen, but I'm not ready to do it (and then deal with the unexpected fallout...).

**Comment by PBfordev** [comment] 2022-03-30 18:53
I tried upgrading doxygen to its latest version (1.8.18 -> 1.9.3): Did not help.

I then checked doxygen.log: There is a couple warnings there but nothing relevant.

I finally decided to follow vadz advice and [create a group for static wxString members](https://github.com/wxWidgets/wxWidgets/commit/b06f59e85799bfa1eedd9b71e8cb60a2f5cb3aaf): At first it seemed it worked but then I noticed that not only it put the static members in the first place, the descriptions for overloads there were also still wrong :(  I tried adding a group description and also creating an unnamed group but to no avail. TBH, I don't even know if one can simply nest groups like that in doxygen.

So I am out of ideas (but I also have basically zero doxygen knowledge).

**Comment by wh11204** [comment] 2022-03-31 08:32
Can you try something like this?

`static const size_t npos;  /**< An 'invalid' value for string index */ `

**Comment by wh11204** [comment] 2022-03-31 11:17
I have tested my proposal above and it does not work, but the attached doxygen.log shows a lot of illegal or unknown commands.

Also, this line `@category{data}` in string.h generates this: `<>< =''>:</>&;&;< =''>\ </></>`

[doxygen.log](https://github.com/wxWidgets/wxWidgets/files/8388807/doxygen.log)

**Comment by vadz** [comment] 2022-03-31 15:05
> I have tested my proposal above and it does not work, but the attached doxygen.log shows a lot of illegal or unknown commands.
> 
> Also, this line `@category{data}` in string.h generates this: `<>< =''>:</>&;&;< =''>\ </></>`

You're not using the latest master, where I've already corrected all this.

**Comment by vadz** [comment] 2022-08-03 17:01
It turns out that this was the same stupid mistake as in #22572 and so should be fixed by the commit above.

**Closed** 2022-08-19 21:50 UTC
Labels: documentation, backport-3.2
