### ISSUE TITLE
wxVListBox black lines between items

### ISSUE THREAD

**Issue by AndersMunch** [wxWidgets/wxWidgets#22562] opened 2022-06-23 10:20 UTC
**Describe the bug**

wxVListBox renders black lines between items, overwriting owner-drawn content.

**Expected vs observed behaviour**

In 3.1.6 and older, the list items appeared as drawn by `OnDrawItem`, as expected.  In 3.1.7, black lines appear between list items. 

**Patch or snippet allowing to reproduce the problem**

Sample program to illustrate:
```python
import wx

class MyVListBox(wx.VListBox):
    def __init__(self, parent):
        super().__init__(parent, -1)
        self.SetItemCount(20)
    def OnMeasureItem(self, n):
        return 10
    def OnDrawItem(self, dc, rect, n):
        col = ['#aaaaaa', '#dddddd'][n%2]
        dc.SetBrush(wx.Brush(col))
        dc.DrawRectangle(rect)

class MyFrame(wx.Frame):
    def __init__(self):
        super().__init__(None, -1, wx.version())
        self._vl = vl = MyVListBox(self)
        self.Layout()

if __name__=='__main__':
    app = wx.App()
    fr = MyFrame()
    fr.Show(True)
    app.MainLoop()
```

In 3.1.5 and 3.1.6, it looks like this:
![billede](https://user-images.githubusercontent.com/10682854/175274225-1ded8666-b5b6-41a7-ad6c-d84fe07f4a10.png)

In 3.1.7, it looks like this:
![billede](https://user-images.githubusercontent.com/10682854/175274339-b0ca7052-9fc8-439b-873a-f232bbf1edb5.png)

In both cases, the `wx.Rect` arguments to `OnDrawItem` calls are adjoining: In the sample program it'll be (x=0,height=10) followed by (x=10,height=10), (x=20, height=10) etc., there are no gaps.

**Platform and version information**
 - wxWidgets version you use: 3.1.7
 - wxWidgets port you use: wxMSW via wxPython
 - OS and its version: Windows 10.0.19044.1766

**Comment by MaartenBent** [comment] 2023-06-15 16:57
These seem indeed regressions from https://github.com/wxWidgets/wxWidgets/pull/2412, though both problems have a different cause.

The first one is caused by the use of `wxDCPenChanger`. IMO this is intended. To fix the border around the drawn rectangles you have to manually set a pen using (or the python equivalent) in your `OnDrawItem`:
```c++
dc.SetPen(*wxTRANSPARENT_PEN);
```

The second problem, in the htlbox sample, is not directly caused by using `EXPLORER::LISTVIEW`, but it did expose the problem. A selected rectangle is drawn for every list item in:
https://github.com/wxWidgets/wxWidgets/blob/d7a98a44ea6c9f814e35db1d1aa869d3b5bf10d1/src/generic/vlbox.cpp#L431-L432

I think this should only be drawn for the selected/current item(s). This would also fix setting the background colour, since now it is overdrawn by the selection box.
I'll create a PR with a fix for this shortly.

**Closed** 2023-06-15 22:04 UTC
Labels: MSW, regression
