### ISSUE TITLE
wxColour names are handled differently by FromString() than by GetAsString() on Linux

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#23518] opened 2023-05-04 08:46 UTC
### Description

The functionality of `wxColour::FromString()` with wxGTK is incompatible with `wxColour::GetAsString()` and is also incompatible with other platforms (e.g. wxMSW).

The incompatible behaviour can be reproduced with the following changes to the minimal sample:
```patch
diff --git "a/samples/minimal/minimal.cpp" "b/samples/minimal/minimal.cpp"
index 5f32257c6b..d317968316 100644
--- "a/samples/minimal/minimal.cpp"
+++ "b/samples/minimal/minimal.cpp"
@@ -120,6 +120,15 @@ bool MyApp::OnInit()
     if ( !wxApp::OnInit() )
         return false;
 
+    wxColour col1( 0, 255, 0 );
+    wxString name = col1.GetAsString(); // Returns the color name 'green'
+    wxColour col2( name );              // With wxGTK (0, 128, 0) instead of (0, 255, 0)
+    if ( col1 != col2 )
+    {
+        wxLogError("Mismatch of color and text: %s -> %s -> %s", col1.GetAsString(wxC2S_CSS_SYNTAX),
+                                                           name, col2.GetAsString(wxC2S_CSS_SYNTAX) );
+    }
+
     // create the main application window
     MyFrame *frame = new MyFrame("Minimal wxWidgets App");
 

```

I think the fix will be to call `FromString()` of the base class first and the platform specific function only as a fallback.
```patch
diff --git "a/src/gtk/colour.cpp" "b/src/gtk/colour.cpp"
index 41b2ae2a11..89441210e0 100644
--- "a/src/gtk/colour.cpp"
+++ "b/src/gtk/colour.cpp"
@@ -260,6 +260,9 @@ wxColour::operator const GdkRGBA*() const
 
 bool wxColour::FromString(const wxString& str)
 {
+    if ( wxColourBase::FromString(str) )
+        return true;
+
 #ifdef __WXGTK3__
     GdkRGBA gdkRGBA;
     if (gdk_rgba_parse(&gdkRGBA, str.utf8_str()))
@@ -276,5 +279,5 @@ bool wxColour::FromString(const wxString& str)
     }
 #endif
 
-    return wxColourBase::FromString(str);
+    return false;
 }

```

### Platform and version information

- wxWidgets version  you use: 3.2.2.1
- wxWidgets port  you use: wxGTK
- OS  and its version: openSUSE Leap 15.1

+ GTK version: 2.24.32
+ Which GDK  backend is used: X11
+ Current theme:

**Comment by vadz** [comment] 2023-05-04 16:43
I guess we should indeed do this as it doesn't make much sense to have platform-specific colours interpretation...

Any objections?

**Comment by paulcor** [comment] 2023-05-04 17:51
It looks like GTK (via Pango) changed to the SVG/CSS definition of "green" 10 years ago. Of course there is no documentation of what definitions we use for color names or where they came from. Long ago an attempt was made to standardize them (bb131fdbc5), but that apparently failed (5e2ab1ea5d). The wxGTK `wxColour` ctor has been using the definitions provided by GTK since 2006 (40989e46b86). Changing that seems very likely to break somebody. I'm not sure what the least-bad option is here.

**Comment by vadz** [comment] 2023-05-04 19:07
The problem for me is inconsistency with `GetAsString()`, it looks like converting a colour to the string and back should really give back the same colour. And as we can't change `GetAsString()` to use GTK names (can we?), this looks like the only thing we can do.

Or I guess we could introduce new functions using CSS-compatible names...

**Comment by paulcor** [comment] 2023-05-06 22:01
> The problem for me is inconsistency with GetAsString()

Well, yes, that **is** the problem. Some possible solutions:
- Use the existing `wxColourDatabase` colors for wxGTK. This risks breaking things, as about 50 of the 70 colors don't match the GTK (`rgb.txt` or CSS) values, which wxGTK has been using for 17 years.
- Change the `wxColourDatabase` colors to standard values. This presumably would have the same compatibility risk as the previous idea. And it was done once already, and almost immediately reverted. Sure would be nice, though, as some of them appear to be just plain wrong (looking at you, "salmon").
- For wxGTK, re-populate `wxColourDatabase` with the GTK values. I tried this out, it's a little ugly but can be done, and would eliminate the round-trip string conversion inconsistency. The colors would remain inconsistent across platforms though.
- Leave the existing mess alone, and introduce a new API. The only way to have full consistency and compatibility. Would probably be more awkward though, and maybe nobody would use it.
- Do nothing, except maybe make a note in the documentation. The inconsistency has been there for 17 years. It must not be much of a problem.

**Comment by paulcor** [comment] 2023-05-08 15:36
> I have no memory of what sort of problems did the original change in 2003 result in

There is some info in #6031.

> perhaps we could make it return the standard CSS names

I don't understand what you're proposing here. The problem is basically that with wxGTK there are two colors with the same name, and it's possible to expose this as shown above in the initial description.

> we have another bunch of colour definitions

It looks like those are from a very old version of X11 `rgb.txt`, so not standard.

**Comment by oneeyeman1** [comment] 2024-07-28 04:12
@vadz ,
If there are 2 entries for a "green", then why not remove one until the final solution can be found?
Especially since it is now results in a crash...

Thank you.

**Comment by vadz** [comment] 2024-11-20 21:26
Returning to this, and just to confirm what we already know, out of 70 colour database entries, only 18 use the same values as GTK. The remaining 52 are:

```
                    AQUAMARINE: #70DB93 != #7FFFD4
                   BLUE VIOLET: #9F5F9F != #8A2BE2
                    CADET BLUE: #5F9F9F != #5F9EA0
                         CORAL: #FF7F00 != #FF7F50
               CORNFLOWER BLUE: #42426F != #6495ED
                    DARK GREEN: #2F4F2F != #006400
                     DARK GREY: #2F2F2F != #A9A9A9
              DARK OLIVE GREEN: #4F4F2F != #556B2F
               DARK SLATE BLUE: #6B238E != #483D8B
                DARK TURQUOISE: #7093DB != #00CED1
                      DIM GREY: #545454 != #696969
                     FIREBRICK: #8E2323 != #B22222
                  FOREST GREEN: #238E23 != #228B22
                          GOLD: #CC7F32 != #FFD700
                     GOLDENROD: #DBDB70 != #DAA520
                  GREEN YELLOW: #93DB70 != #ADFF2F
                         GREEN: #00FF00 != #008000
                    INDIAN RED: #4F2F2F != #CD5C5C
                         KHAKI: #9F9F5F != #F0E68C
                    LIGHT BLUE: #BFD8D8 != #ADD8E6
                    LIGHT GREY: #C0C0C0 != #D3D3D3
              LIGHT STEEL BLUE: #8F8FBC != #B0C4DE
                    LIME GREEN: #32CC32 != #32CD32
                        MAROON: #8E236B != #800000
             MEDIUM AQUAMARINE: #32CC99 != #66CDAA
                   MEDIUM BLUE: #3232CC != #0000CD
                 MEDIUM ORCHID: #9370DB != #BA55D3
              MEDIUM SEA GREEN: #426F42 != #3CB371
             MEDIUM SLATE BLUE: #7F00FF != #7B68EE
           MEDIUM SPRING GREEN: #7FFF00 != #00FA9A
              MEDIUM TURQUOISE: #70DBDB != #48D1CC
             MEDIUM VIOLET RED: #DB7093 != #C71585
                 MIDNIGHT BLUE: #2F2F4F != #191970
                          NAVY: #23238E != #000080
                    ORANGE RED: #FF007F != #FF4500
                        ORANGE: #CC3232 != #FFA500
                        ORCHID: #DB70DB != #DA70D6
                    PALE GREEN: #8FBC8F != #98FB98
                          PLUM: #EAADEA != #DDA0DD
                        PURPLE: #B000FF != #800080
                        SALMON: #6F4242 != #FA8072
                     SEA GREEN: #238E6B != #2E8B57
                        SIENNA: #8E6B23 != #A0522D
                      SKY BLUE: #3299CC != #87CEEB
                    SLATE BLUE: #007FFF != #6A5ACD
                    STEEL BLUE: #236B8E != #4682B4
                           TAN: #DB9370 != #D2B48C
                     TURQUOISE: #ADEAEA != #40E0D0
                    VIOLET RED: #CC3299 != #D02090
                        VIOLET: #4F2F4F != #EE82EE
                         WHEAT: #D8D8BF != #F5DEB3
                  YELLOW GREEN: #99CC32 != #9ACD32
```

And differences for some of them are really huge, so it seems pretty clear that changing this will indeed break a lot of things. Still, if we don't do it now, we're probably never going to do it at all, so I think we should:

1. Change `wxColourDatabase` to use (all) [CSS colours](https://www.w3.org/TR/css-color-4/#named-colors) values by default.
2. Add a possibility to switch to the old colours in some way. The simplest would be to add some `wxColourDatabase::UseColourScheme()` which would take either "CSS" or "old" value.
3. Maybe remove `wxColour::FromString()` from wxGTK as it should be identical to the new default behaviour.

Should we do this before 3.3.0 or should we close this as "won't fix" and never do anything about it at all?

**Comment by vadz** [comment] 2024-12-23 17:54
This should be fixed now, please let me know if any problems (other than being incompatible with the previous wxMSW versions) still remain.

**Closed by vadz** 2024-12-23 17:54 UTC
Labels: GTK, confirmed
