### ISSUE TITLE
Disappearing modal dialogs on macOS when using "Spaces"

### ISSUE THREAD

**Issue by andymrob** [wxWidgets/wxWidgets#22242] opened 2022-03-29 14:51 UTC
**Describe the bug**
When a modal dialog is dragged to the second display, it disappears at the moment the mouse button is released.

**Expected vs observed behaviour**
Naturally we would not expect it to vanish!

**To Reproduce**, **Platform and version information**

This is an M1 Mac Mini running OS 12.3 with two DELL displays attached. The problem doesn't seem to happen on OS 11 Intel. This was reported to me by a user so it's not just me.

Using wx head with:
../configure --enable-debug --with-macosx-version-min=11.0 --enable-macosx_arch=arm64

- Build and run the dialogs sample.
- On the Dialogs menu select the first item "Message box".
- Drag the resulting dialog to the second display and release the mouse button.
- Everything is fine. Close that dialog.
- On the Dialogs menu select the third item "Message dialog".
- Drag the resulting dialog to the second display and release the mouse button.
- The dialog disappears!!!
- Hit escape. This closes the invisible dialog and the application has not crashed.

I've made a little video as it seems so strange:
https://www.seventhstring.com/otherY/DisappearingDialog.mov

I can see that wxMessageBox uses wxMessageDialog which does this:
	NSAlert* alert = (NSAlert*)ConstructNSAlert();
	OSXBeginModalDialog();
	int button = -1;
	button = [alert runModal];
	OSXEndModalDialog();
This works ok.

While wxDialog uses wxDialog::ShowModal which does this:
	wxModalEventLoop modalLoop(this);
	m_eventLoop = &modalLoop;
	OSXBeginModalDialog();
	modalLoop.Run();
	OSXEndModalDialog();
This vanishes.

I suppose this could be a macOS bug but there is probably some way around it. However I'm a bit out of my depth.

**Comment by vadz** [comment] 2022-03-29 17:52
Sorry, I have absolutely no idea about what's going on here and can't even try reproducing it (I don't have a multimonitor Mac system).

Could you please add a `printf()` on a timer showing the dialog position/size to at least try to formulate some hypothesis about what's going on here?

**Comment by imciner2** [comment] 2022-03-30 01:07
I think what the reporter is describing is actually a side effect of a new macOS feature called "Spaces". It will probably be fixed if you uncheck the option for "Displays have separate Spaces" in the Mission Control settings. We had this reported in a downstream wxWidgets-using application, and this is what seemed to fix it (https://gitlab.com/kicad/code/kicad/-/issues/8471#note_882735946).

**Comment by andymrob** [comment] 2022-03-30 07:23
Hi Ian,

You're right, that fixes it.

But surely this behaviour cannot be intended by Apple - that a dialog 
should simply be lost with no way of finding it.

Also of course it happens with some modal dialogs but not others, as I 
described before.

The thread you refer to doesn't seem to have any solution, except "Yes, 
I suppose we could reject a move that takes the dialog off-screen.  That 
would seem kind of annoying to users, but less annoying than the dialog 
disappearing completely :)".

Anyway thank you, this certainly helps understand what is happening,

Regards,
Andy Robinson, Seventh String Software, www.seventhstring.com

**Comment by vadz** [comment] 2022-03-30 12:09
Yes, I agree that we're probably still doing something wrong to make it fail with "Spaces". I still don't know what exactly, but maybe we should be setting `NSWindow.collectionBehavior` to something different?

**Comment by andymrob** [comment] 2022-03-31 11:29
It's a reasonable idea but I've just tried the 3 likely-looking options 
and none of them make any difference:

NSWindowCollectionBehaviorCanJoinAllSpaces
NSWindowCollectionBehaviorMoveToActiveSpace
NSWindowCollectionBehaviorManaged

Regards,
Andy Robinson, Seventh String Software, www.seventhstring.com

**Comment by vadz** [comment] 2022-03-31 15:15
Thanks for testing and sorry that it didn't work. Unfortunately I don't really know what else could we do to solve this, so I can only hope @csomor or @vslavik might have some idea.

**Comment by csomor** [comment] 2022-04-23 13:20
It took me a while to get to the root, not that I have found a solution, but at least we know the source: 

The problem is with the native child-parent relationship of the dialog with the frame (`NSWindow addChildWindow`), the dialog is moved to a different space than its parent, and since this problem also is present within a simple swift app, it's not some low level detail we are doing wrongly:

https://stackoverflow.com/questions/71213724/stop-child-nswindow-disappearing-when-moved-to-another-screen

Google search reveals strange bugs like this and side effects for the usage of `addChildWindow`, so I guess we will have to reduce our usage for this layering where ever possible.

**Comment by csomor** [comment] 2022-04-23 14:08
@andymrob Hi Andy, could you please just test whether you encounter problems if you just comment out line 959 in `src/osx/cocoa/nonownedwnd.mm` where the `addChildWindow` is happening. Thanks.

**Comment by andymrob** [comment] 2022-04-23 15:51
Thanks for looking into this and yes, that does fix it and I don't immediately see any problem - so is this a solution? It looks like it to me.

**Comment by whalley** [comment] 2022-05-29 17:59
Is there a plan to fix this?

**Comment by csomor** [comment] 2022-05-29 18:47
> Is there a plan to fix this?

does the workaround I gave to Andy solve the problem for you too ?

**Comment by whalley** [comment] 2022-05-29 23:36
@csomor Yes Stefan, the change you identified does indeed solve the issue for me with no apparent ill effect.

**Comment by andymrob** [comment] 2022-05-30 07:08
I also have seen no bad effect.

Regards,
Andy Robinson, Seventh String Software, www.seventhstring.com

**Comment by vadz** [comment] 2022-05-30 15:45
@csomor Let's remove this line then (I'd prefer if you did it, with a hopefully useful commit message explaining this change, but it's a simple enough change for me to do it myself if really needed) before 3.1.7, like this we'll get at least some testing before 3.2.0. Please let me know if you agree (or, better yet, please do it). TIA!

**Comment by csomor** [comment] 2022-05-30 16:52
@vadz ok, committed

**Closed** 2022-05-30 16:51 UTC
Labels: macOS
