### ISSUE TITLE
wxaui demo (auidemo): when managed panes are resized, the captions are smeared on repaint (Linux, Gtk)

### ISSUE THREAD

**Issue by wxprospero** [wxWidgets/wxWidgets#22776] opened 2022-09-05 18:01 UTC
wx 3.3 (github head, 9/4/22), Gtk+ 3.24.24, Fedora 36 (Wayland).

Pic shows the smeared captions after resizing the panes:

![Screenshot from 2022-09-04 23-46-09](https://user-images.githubusercontent.com/99424160/188497624-b2b0013e-7275-4daf-be0e-0814ad7b7160.png)

It's also possible to cause a crash by resizing the bottom pane up and down and clicking on the border of the caption fast enough, just before the drag stops. Pic shows the crash message:

![Screenshot from 2022-09-04 23-50-07](https://user-images.githubusercontent.com/99424160/188498107-00756953-f60e-41b0-928f-979fa2bf2822.png)

**Comment by paulcor** [comment] 2022-09-05 19:14
I suspect this is caused by AUI drawing with `wxClientDC`.

**Comment by wxprospero** [comment] 2022-09-06 03:03
Sadly, it seems the crash is reproducible outside of auidemo. This sample program (which does no event handling) can be used to produce it, at least if you manipulate the divider just the right way by sliding it back and forth and clicking the edge in the right place while still in motion (I can record a video of it, if needed):

[code]#include <wx/app.h>
#include <wx/wx.h>
#include <wx/frame.h>
#include <wx/aui/framemanager.h>

class MyFrame: public wxFrame {
	public:
	MyFrame() : wxFrame(nullptr, wxID_ANY, "Test")
	{
		m_manager.SetManagedWindow(this);
		
		m_page = new wxPanel(this);
		wxBoxSizer *page_sizer = new wxBoxSizer(wxHORIZONTAL);
		page_sizer->Add(new wxButton(m_page, wxID_ANY, "Push Me"));
		m_page->SetSizer(page_sizer);

		m_page2 = new wxPanel(this);
		wxBoxSizer *page2_sizer = new wxBoxSizer(wxHORIZONTAL);
		page2_sizer->Add(new wxTextCtrl(m_page2, wxID_ANY), 1, wxEXPAND);
		m_page2->SetSizer(page2_sizer);

		m_manager.AddPane(m_page, wxLEFT, "Pane Caption1");
		m_manager.AddPane(m_page2, wxCENTER, "Pane Caption2");
		m_manager.Update();
	}
	private:
		wxPanel *m_page;
		wxPanel *m_page2;
		wxAuiManager m_manager;
};

class MyApp : public wxApp {
	public:
		bool OnInit() override
		{
			MyFrame* frame = new MyFrame();
			this->SetTopWindow(frame);
			frame->Show();
			return true;
		}
};

wxDECLARE_APP(MyApp);
wxIMPLEMENT_APP(MyApp);[/code]

![Screenshot from 2022-09-05 23-00-10](https://user-images.githubusercontent.com/99424160/188538314-2929e664-a556-42a1-b9e3-86754477809a.png)

**Comment by vadz** [comment] 2022-09-06 10:24
Just a note: while this is certainly a bug which needs to be fixed (probably 2 different bugs, in fact), this is _not_ a crash and shouldn't be visible to the end users of your application at all if you don't enable debugging in production builds, as explained in [the docs](https://docs.wxwidgets.org/latest/overview_debugging.html#overview_debugging_config).

**Comment by vadz** [comment] 2023-12-26 15:13
This was marked as "confirmed" but I can't actually reproduce this. What exactly needs to be done in order to see the problem? I think the repaint problem might have been fixed in 12497372fc (Fix painting artifacts with AUI and wxGTK3 in some environments, 2023-01-13) but I don't see any commits that could have fixed the assert since 2022-04-09.

Could you please retest this with the current master i.e. 400ce8b582 (Return null from wxGetX11Display() when using Wayland, 2023-12-25) and check if these problems still happen and provide the exact instructions for reproducing them if they do? TIA!

**Comment by paulcor** [comment] 2023-12-27 17:32
> I think the repaint problem might have been fixed in 1249737

It's trivially easy to check this by reverting that one line change. I have now done so and verify that the problem seems to be fixed.

**Closed** 2023-12-27 18:06 UTC
Labels: GTK, repro needed, Wayland, AUI
