### ISSUE TITLE
wxMac: wxTreeCtrl / wxTreeBook highlight color is not great

### ISSUE THREAD

**Issue by craftyjon** [wxWidgets/wxWidgets#24605] opened 2024-06-12 02:16 UTC
### Description

The selected-item highlight color used in wxTreeCtrl and wxTreeBook is very low-contrast with the text in both light and dark modes on wxMac.  Screenshots from treectrl sample (item 2 is selected; item 3 has a manual style)

Light mode:

<img width="406" alt="image" src="https://github.com/wxWidgets/wxWidgets/assets/116737/1cb2b29a-434f-4e0e-a65e-43a3165075de">

Dark mode:

<img width="362" alt="image" src="https://github.com/wxWidgets/wxWidgets/assets/116737/76c680c7-84ad-4f70-afb6-fdb901686e18">

For comparison, wxListCtrl works ok:

<img width="408" alt="image" src="https://github.com/wxWidgets/wxWidgets/assets/116737/4581651e-f620-4e84-9bfe-09ca9c92c4b1">

<img width="353" alt="image" src="https://github.com/wxWidgets/wxWidgets/assets/116737/359ce3e9-2e55-4bdf-98f9-43abb966f3d4">

### Platform and version information

- wxWidgets version  you use: 3.2.5
- wxWidgets port  you use: wxOSX
- OS  and its version: macOS 14.4

**Comment by HenkDemper** [comment] 2024-06-21 20:06
I have the same issue here on macOS 14.5

I think the gray color that you are seeing is the unfocused color.
When selected and the control has focus, tree or list controls should be drawn with the system focus color, like blue in my case, which works fine in wxWidget 3.2.4:
![Focus](https://github.com/wxWidgets/wxWidgets/assets/23651943/1cbcf076-a2e0-4f11-a879-e00cfc70bd0a)
But since wxWidgets 3.2.5, at least wxListCtrl and wxTreeCtrl (and wxGenericDirCtrl using it) always show their selection in gray, so it is difficult to see which control (if you use multiple) currently has focus.
If the control looses focus, the selected items are drawn correctly in gray in both wxWidgets 3.2.4 and 3.2.5

Furthermore in the identically build listctrl.app and treectrl.app it seems keyboard interception is lost, only a short beep is sound when you press a key in 3.2.5. In wxWidgets 3.2.4 (see screenshot above) you will see keyboard notifications in the message pane as expected...

I also tested latest git snapshot today and the problems are both present.
It seems something focus colour & keyboard message handling is broken, at least for list and tree controls (text controls appear Ok) on Mac...

**Comment by csomor** [comment] 2024-07-05 07:14
related to #24667

**Comment by csomor** [comment] 2024-07-05 18:20
@craftyjon @HenkDemper could you please test with the commit from the PR #24678, especially test whether this leads to other anomalies within the listctrl / treectrl, thanks

**Comment by HenkDemper** [comment] 2024-07-05 20:58
Hi @csomor.

By coincidence yesterday I was also debugging and by comparing 3.2.4 and 3.2.5 sources found I could fix things (focus color and keyboard control) by using 3.2.5 with only the files window.mm, window_osx.cpp and private.h rolled back from 3.2.4. Those are the same files from commits abab8b4 and b8744be as described in #24667.

I just applied your 2 changes in window.mm from #24678, then build and tested with both my own wxWidgets application I'm developing (were I encountered the issues) as well as in the listctrl.app and treectrl.app samples. They all now seem to function correctly again regarding focus colours (blue under Sonoma) and keyboard handling (I can browse through the items), no other/new issues encountered in either list/tree controls.

So AFAIK the fix from #24678 (it was not obvious for me 😉) is Ok 👍🏻.
I assume it will be pushed onto git master eventually ?

Thanks !

**Comment by csomor** [comment] 2024-07-06 05:00
Hi @HenkDemper 

> So AFAIK the fix from #24678 (it was not obvious for me 😉) is Ok 👍🏻. I assume it will be pushed onto git master eventually ?

thanks for testing!

yes, this PR will be merged with master and backported to 3.2 once we can be reasonable sure not to introduce other regressions

**Closed** 2024-07-07 22:18 UTC
