### ISSUE TITLE
wxGLCanvas init crash with SCROLL flag under MACOS 10.15.7

### ISSUE THREAD

**Issue by idealsu** [wxWidgets/wxWidgets#23536] opened 2023-05-10 10:09 UTC
version, 3.2.2.1
wxGLCanvas cannot be initialized with wxVSCROLL flag
	canvas = new wxGLCanvas(
	this
	, wxID_ANY
	, NULL
	, wxPoint(0, 0)
	, wxDefaultSize
	, wxHSCROLL | wxVSCROLL);//crash for scrollbar, BUT it work under windows

how to support scrollbar for glcanvas

**Comment by vadz** [comment] 2023-05-10 14:03
Does it actually crash? If so, please show us the stack when it crashes (see [bug submission guidelines](https://www.wxwidgets.org/develop/how-to-report-issues/)).

**Comment by idealsu** [comment] 2023-06-15 05:08
> Does it actually crash? If so, please show us the stack when it crashes (see [bug submission guidelines](https://www.wxwidgets.org/develop/how-to-report-issues/)).

stack below:
![wxglcanvs scrollbar crash](https://github.com/wxWidgets/wxWidgets/assets/5327883/f3568c67-834b-48b4-a3ac-6187e62d30ec)

**Comment by vadz** [comment] 2023-06-15 19:15
Thanks, but as you are already in the debugger, could you please check if peer is null somehow here? It would also be helpful to see the full stack, ideally as text (please copy-paste it) and not as a screenshot.

Finally, having a way to reproduce the bug is always very helpful. Can you reproduce the problem in e.g. samples/opengl/cube sample if you add `wxVSCROLL` flag to it?

**Comment by idealsu** [comment] 2023-06-17 14:08
YES, peer is invalid. OSX port not impl?

# variable 

wxOSXWidgetImpl* wxWindowMac::GetPeer() const 
{ 
    return m_peer == kOSXNoWidgetImpl ? NULL : m_peer ; 
}

m_peer	wxOSXWidgetImpl *	0xffffffffffffffff
kOSXNoWidgetImpl	wxWidgetImplType *	0xffffffffffffffff

# stack

#0	0x00000001007f97cc in wxWindow::GetPeer() const at /wxWidgets-3.2.2.1/src/osx/window_osx.cpp:275
#1	0x00000001007fbe04 in wxWindow::DoGetClientSize(int*, int*) const at /wxWidgets-3.2.2.1/src/osx/window_osx.cpp:817
#2	0x000000010008598c in wxWindowBase::GetClientSize(int*, int*) const at /wxWidgets-3.2.2.1/include/wx/window.h:333
#3	0x00000001007fa182 in wxWindow::MacCreateScrollBars(long) at /wxWidgets-3.2.2.1/src/osx/window_osx.cpp:2071
#4	0x00000001007f90e3 in wxWindow::Create(wxWindow*, int, wxPoint const&, wxSize const&, long, wxString const&) at /wxWidgets-3.2.2.1/src/osx/window_osx.cpp:411
#5	0x0000000100b0e1ab in wxGLCanvas::DoCreate(wxWindow*, int, wxPoint const&, wxSize const&, long, wxString const&) at /wxWidgets-3.2.2.1/src/osx/cocoa/glcanvas.mm:168
#6	0x0000000100b0f7f4 in wxGLCanvas::Create(wxWindow*, wxGLAttributes const&, int, wxPoint const&, wxSize const&, long, wxString const&, wxPalette const&) at /wxWidgets-3.2.2.1/src/osx/glcanvas_osx.cpp:501
#7	0x0000000100b0fa84 in wxGLCanvas::Create(wxWindow*, int, wxPoint const&, wxSize const&, long, wxString const&, int const*, wxPalette const&) at /wxWidgets-3.2.2.1/src/osx/glcanvas_osx.cpp:471
#8	0x0000000100b0f94a in wxGLCanvas::wxGLCanvas(wxWindow*, int, int const*, wxPoint const&, wxSize const&, long, wxString const&, wxPalette const&) at /wxWidgets-3.2.2.1/src/osx/glcanvas_osx.cpp:452

**Comment by vadz** [comment] 2023-06-17 14:18
OK, thanks, the problem is that `DoGetClientSize()` tries to access the peer before it has been set in `wxGLCanvas::DoCreate()`.

@csomor I'd really appreciate your guidance here because while I see several ways to fix this, I'm not sure which one is the best/least worst one. Should we move `MacCreateScrollBars()` to `MacPostControlCreate()` perhaps?

**Comment by csomor** [comment] 2023-06-17 14:23
@vadz I'll look at it, btw I'm not even sure OpenGL on Mac will work properly when scrolled

**Comment by vadz** [comment] 2023-06-17 14:31
Thanks! We can, of course, just turn off scrolling styles in `wxGLCanvas::DoCreate()` but I think this might be not the only class affected by this as basically any other window calling `DontCreatePeer()` before `wxWindow::Create()` would crash in the same way if scroll styles are used.

**Comment by csomor** [comment] 2023-06-17 15:31
@vadz yes I agree, so at the moment I'd perhaps guard in MacCreateScrollBars with  
  
`if ( style & ( wxVSCROLL | wxHSCROLL )` **&& m_peer != kOSXNoWidgetImpl** `)`

as I'm relucant to move everything into MacPostControlCreate right now. 
But your right as this would be the second place to call MacCreateScrollBars if there wasn't a native peer available before.

**Comment by vadz** [comment] 2023-06-17 15:43
The question is whether we can use scrollbars with OpenGL canvas or not. If we can't anyhow, then this is not worse than any other fix. But if we can, we shouldn't do this.

**Comment by csomor** [comment] 2023-06-17 15:58
@vadz right now, when I move things into MacPostControlCreate then the scrollbars are created but have no effect. So someone would have to take the time to look into the options.

**Comment by csomor** [comment] 2023-06-17 16:00
But of course this would at least offer the option for extending the functionality.

**Comment by csomor** [comment] 2023-06-17 16:02
so I'd be fine with moving this down to MacPostControlCreate, and use m_windowStyle since we don't have the style param anymore, it doesn't change the timing for the situations which worked up to now - I was not remembering correctly and though it was otherwise.

**Comment by vadz** [comment] 2023-06-18 15:45
Please see #23649 (sorry for the broken first version).

**Closed** 2023-06-19 12:44 UTC
Labels: macOS
