### ISSUE TITLE
Selected item not visible in a disabled wxListBox under Ubuntu

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22215] opened 2022-03-22 07:44 UTC
This issue also happens with wxWidgets-3.1.5, not only with the the latest master for the upcoming 3.1.6.

It can be reproduced in the **widgets sample** using the following changes.
```patch
diff --git "a/samples/widgets/listbox.cpp" "b/samples/widgets/listbox.cpp"
index c8865b22a2..ad9adbc600 100644
--- "a/samples/widgets/listbox.cpp"
+++ "b/samples/widgets/listbox.cpp"
@@ -54,6 +54,7 @@
 enum
 {
     ListboxPage_Reset = wxID_HIGHEST,
+    ListboxPage_Disable,
     ListboxPage_Add,
     ListboxPage_AddText,
     ListboxPage_AddSeveral,
@@ -110,6 +111,7 @@ protected:
     void OnListboxDClick(wxCommandEvent& event);
     void OnCheckListbox(wxCommandEvent& event);
 
+    void OnCheckDisable(wxCommandEvent& event);
     void OnCheckOrRadioBox(wxCommandEvent& event);
 
     void OnUpdateUIAddSeveral(wxUpdateUIEvent& event);
@@ -170,6 +172,7 @@ protected:
     wxCheckBox *m_chkVScroll,
                *m_chkHScroll,
                *m_chkSort,
+               *m_chkDisable,
                *m_chkOwnerDraw;
 
     // the listbox itself and the sizer it is in
@@ -227,6 +230,7 @@ wxBEGIN_EVENT_TABLE(ListboxWidgetsPage, WidgetsPage)
     EVT_LISTBOX_DCLICK(ListboxPage_Listbox, ListboxWidgetsPage::OnListboxDClick)
     EVT_CHECKLISTBOX(ListboxPage_Listbox, ListboxWidgetsPage::OnCheckListbox)
 
+    EVT_CHECKBOX(ListboxPage_Disable, ListboxWidgetsPage::OnCheckDisable)
     EVT_CHECKBOX(wxID_ANY, ListboxWidgetsPage::OnCheckOrRadioBox)
     EVT_RADIOBOX(wxID_ANY, ListboxWidgetsPage::OnCheckOrRadioBox)
 wxEND_EVENT_TABLE()
@@ -256,6 +260,7 @@ ListboxWidgetsPage::ListboxWidgetsPage(WidgetsBookCtrl *book,
     m_chkVScroll =
     m_chkHScroll =
     m_chkSort =
+    m_chkDisable =
     m_chkOwnerDraw = (wxCheckBox *)NULL;
 
     m_lbox = NULL;
@@ -317,6 +322,7 @@ void ListboxWidgetsPage::CreateContent()
                    );
     m_chkSort = CreateCheckBoxAndAddToSizer(sizerLeft, "&Sort items");
     m_chkOwnerDraw = CreateCheckBoxAndAddToSizer(sizerLeft, "&Owner drawn");
+    m_chkDisable = CreateCheckBoxAndAddToSizer(sizerLeft, "Disable", ListboxPage_Disable);
 
     sizerLeft->Add(5, 5, 0, wxGROW | wxALL, 5); // spacer
     sizerLeft->Add(m_radioSelMode, 0, wxGROW | wxALL, 5);
@@ -721,6 +727,11 @@ void ListboxWidgetsPage::OnCheckListbox(wxCommandEvent& event)
     wxLogMessage( "Listbox item %d toggled", event.GetInt() );
 }
 
+void ListboxWidgetsPage::OnCheckDisable(wxCommandEvent& event)
+{
+    m_lbox->Enable( !event.IsChecked() );
+}
+
 void ListboxWidgetsPage::OnCheckOrRadioBox(wxCommandEvent& WXUNUSED(event))
 {
     CreateLbox();

```

**To Reproduce**
1. Go to page 'Native / Listbox'
2. Click on 'Insert a few strings'
3. Select an item in the listbox
   ![listbox-with-selection_enabled](https://user-images.githubusercontent.com/99262969/159431266-2ca744a2-1033-45b9-9cc0-d6ff6c42a04e.png)
4. Click the 'Disable' check box
5. See error: The selected item is not visible (probably because the font and background color are identical).
   ![listbox-with-selection_disabled](https://user-images.githubusercontent.com/99262969/159431364-5b477191-4658-47d4-8006-9331699feff0.png)

**Platform and version information**
 - wxWidgets version you use: **Latest master** for upcoming 3.1.6
 - wxWidgets port you use: **wxGTK**
 - OS and its version: Ubuntu 20.04
 - For wxGTK only:
   + GTK version: 2.24.31
   + Which GDK backend is used: X11

**Comment by vadz** [comment] 2022-03-22 16:31
This is probably Ubuntu(-theme) specific again as I can't reproduce it under Debian (I didn't modify the widgets sample because there is already a menu item to disable the control in it, so I just pressed `Ctrl-E` to do it, but the effect should be exactly the same).

I don't see anything obviously wrong in our code. I wonder if doing nothing (i.e. not calling `GTKApplyStyle()`) in `wxListBox::DoApplyWidgetStyle()` changes anything for you?

**Comment by taler21** [comment] 2022-03-23 07:08
> This is probably Ubuntu(-theme) specific again as I can't reproduce it under Debian (I didn't modify the widgets sample because there is already a menu item to disable the control in it, so I just pressed `Ctrl-E` to do it, but the effect should be exactly the same).

Thanks for pointing out the already existing menu item for deactivating the control.
Using it has the same effect, yes.

I have now tested it on several different systems.
Under openSUSE 42.3 (with KDE desktop) it's just as invisible as under Ubuntu 20.04.
Under Linux Mint 20, Fedora 35 and CentOS 7 it's a little bit visible (white text on a light gray background).

openSUSE 42.3 (KDE desktop with 'Adwaita' theme for GTK2 applications):
![listbox_openSUSE-42-3_Adwaita](https://user-images.githubusercontent.com/99262969/159641078-133bf68d-acab-4163-b9ff-9f0ce2c02c89.png)

openSUSE 42.3 (KDE desktop with 'Breeze' theme for GTK2 applications):
![listbox_openSUSE-42-3_Breeze](https://user-images.githubusercontent.com/99262969/159641101-9d5ad5c3-011d-4b8c-ab93-ef9cbb93fbab.png)

Linux Mint 20 (similar under Fedora 35 and CentOS 7):
![listbox_Linux-Mint-20](https://user-images.githubusercontent.com/99262969/159641121-95aed8fc-0fab-476d-9fc1-60535225a388.png)

Ubuntu 18.04:
![listbox_Ubuntu-18-04](https://user-images.githubusercontent.com/99262969/159641232-de1d1fc7-8854-40f7-8bac-bca422cc9a62.png)

> I don't see anything obviously wrong in our code. I wonder if doing nothing (i.e. not calling `GTKApplyStyle()`) in `wxListBox::DoApplyWidgetStyle()` changes anything for you?

No, not calling `GTKApplyStyle()` in `wxListBox::DoApplyWidgetStyle()` does not change anything.

**Comment by paulcor** [comment] 2022-03-28 23:14
> We'd need to test a pure GTK example using GtkTreeView in disabled state

You already did, see #18400

**Comment by vadz** [comment] 2022-03-29 17:57
Thanks for the reminder, I've indeed totally forgotten about it. And this really looks like the same bug, except that the other one was about GTK 2 -- but apparently the same problem exists with GTK 3 too. Still, it seems to make more sense to combine both of them, so let's close this one and keep the older one open.

**Closed by vadz** 2022-03-29 17:57 UTC
Labels: GTK

**Comment by paulcor** [comment] 2022-03-29 18:06
> And this really looks like the same bug, except that the other one was about GTK 2

AFAICT, this one is also GTK2.

**Comment by vadz** [comment] 2022-03-29 18:16
Oh, you're right, of course, it was there just in front of me. I have no idea why did I decide this was with GTK 3. Sorry and thanks for correcting me.
