### ISSUE TITLE
wxAuiToolBarItem returned from wxAuiToolBar::AddTool becomes invalid later

### ISSUE THREAD

**Issue by BigMuscle85** [wxWidgets/wxWidgets#23514] opened 2023-05-02 19:11 UTC
### Description

When I build the latest Git code, the following wxAUI code behaves wrong:

```
    m_toolbar = new wxAuiToolBar(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxAUI_TB_DEFAULT_STYLE | wxAUI_TB_HORIZONTAL | wxAUI_TB_HORZ_TEXT);
    m_toolbar->SetToolTextOrientation(wxAUI_TBTOOL_TEXT_BOTTOM);
    wxAuiToolBarItem* newKitTool = m_toolbar->AddTool(wxID_ANY, wxT("New kit"), wxBitmap("new_kit.png", wxBITMAP_TYPE_PNG));
    wxAuiToolBarItem* openKitTool = m_toolbar->AddTool(wxID_ANY, wxT("Open kit"), wxBitmap("open_kit.png", wxBITMAP_TYPE_PNG));
    m_toolbar->AddSeparator();
```

Pointer "openKitTool" seems to be correct after the call to AddTool() but it becomes invalid during the next call to AddSeparator(). I tried debugging the code and it seems that the list of items is recreated in auibar.cpp when "m_items.Add(item);" is called. This results that all previously returned pointers to toolbar items become invalid (because AddTool() returned the pointer to the original list)

### Platform and version information

- wxWidgets version: Git clone from 2023-05-01 (built with VS 2019)
- wxWidgets port: wxMSW
- OS: Windows 10 21H2 (19044)

**Comment by rcane** [comment] 2023-05-03 14:07
I can confirm this problem. It was caused by bc23b1f (Use wxBaseArray instead of object array for wxAuiToolBarItemArray). Before this commit, the toolbar items where effectively saved inside a `wxBaseObjectArray<wxAuiToolBarItem>` which is derived from `wxBaseArray<T*>`. This means the container saved pointers to the actual items. After that commit the items are now saved inside a `wxBaseArray<wxAuiToolBarItem>` which saves the item objects directly. This will invalidate a pointer to an item as soon as the array needs to reallocate its internal memory.

We could just document that a `wxAuiToolBarItem*` returned by any method of `wxAuiToolBar` is only valid until any other method of `wxAuiToolBar` is called. But this is very easy to forget and forces client code into an ugly usage pattern.

So the only option I see is to revert the change and go back to `wxBaseObjectArray`.
But let's see what @vadz has to say about it. Maybe I overlooked something.

**Comment by vadz** [comment] 2023-05-03 17:03
This is indeed a bad problem, thanks for reporting it.

We're probably indeed going to have to revert this commit as I don't see any other way to fix this neither. Maybe we could at least avoid using a macro here as we don't need to define this container in the `.cpp` file because full `wxAuiToolBarItem` declaration is available in the header, and so not use the macros...

**Comment by vadz** [comment] 2023-05-06 19:05
Should be fixed by the linked PR now, please let me know if you still see any problems with it.

**Closed** 2023-05-08 14:15 UTC
Labels: regression
