### ISSUE TITLE
wxFileDialog allows to save a file with an extension different from the wildcard specification

### ISSUE THREAD

**Issue by pkhoan** [wxWidgets/wxWidgets#22088] opened 2022-02-03 21:38 UTC
**Describe the bug**
Normally, wxFileDialog should NOT allow user to save a file with an extension different from the wildcard specification.

For example, I create a dialog with the command:

	wxFileDialog saveFileDialog(this, _("DXF File"), "", "", "DXF file (*.dxf)|*.dxf", wxFD_SAVE | wxFD_OVERWRITE_PROMPT);

Suppose there is only 1 file named **_test.pdf_** in the current directory.

- If I enter the string : **_test_** in the field File Name then `saveFileDialog.GetPath()` returns **_test.dxf_** which is correct.
- If I enter the string : **_test.txt_** in the field File Name then `saveFileDialog.GetPath()` returns **_test.txt.dxf_** which is correct.
- **BUT** If I enter the string : **_test.pdf_** in the field File Name then `saveFileDialog.GetPath()` returns **_test.pdf_** which is **wrong**. It means that an existing file with a different extension can be accidentally  overwritten despite of the wildcard specification. In this case, `saveFileDialog.GetPath()` should return **_test.pdf.dxf_** .

**Platform and version information**
 - wxWidgets version: 3.1.5
 - OS: Windows 10.0.19044.1503

**Comment by vadz** [comment] 2022-02-07 23:16
I can't reproduce this behaviour in the dialogs sample which uses pretty [similar code](https://github.com/wxWidgets/wxWidgets/blob/f0c6b42ad032c2d8651f8cceeb9407bb7ce82b1d/samples/dialogs/dialogs.cpp#L1818).

Entering `test.pdf` returns `test.pdf`, of course, but not before asking if I want to overwrite the file with this name if it exists, which seems like exactly the right behaviour. Have you actually tested with an existing `test.pdf` file?

**Comment by pkhoan** [comment] 2022-02-08 00:05
Actually, it does ask for the overwrite confirmation which is normal because of the flag `wxFD_OVERWRITE_PROMPT` . 

What makes me confusing is why it doesn't append the default the extension given in the wildcard (*.dxf in this example) to the filename if the filename doesn't have this extension BEFORE it checks if the filename exists ?

The wildcard role is to **force user to use a filename with some predefined extensions**. That why I find completely logical that : 
- enter **_test.dxf_** --> check existence of  **_test.dxf_** and return **_test.dxf_** with `GetPath()`
- enter **_test_** --> default extension **_.dxf_** not found --> append **_.dxf_** --> check existence of  **_test.dxf_** and return **_test.dxf_** with `GetPath()`
- enter **_test.txt_** --> default extension **_.dxf_** not found --> append **_.dxf_** -->  check existence of **_test.txt.dxf_** and return **_test.txt.dxf_** with `GetPath()`

and by a similar logic : 
- when user enters **_test.pdf_** --> default extension not found --> it SHOULD append **_.dxf_** (just like the case of **_test.txt_**) --> check existence of **_test.pdf.dxf_**, but NOT existence of **_test.pdf_**

**Comment by PBfordev** [comment] 2022-02-08 06:22
@pkhoan, I do think you may not be correct in your assumptions, at least not when considering the Windows behaviour.

Firstly, AFAICT, `wxFileDialog` has no default extension: The wildcard string can contain multiple extensions and there is not method to tell it which is the default.

Secondly, [the documentation](https://docs.microsoft.com/en-us/windows/win32/api/commdlg/ns-commdlg-openfilenamea#members) for the native API which does have the default extension states (emphasis mine): 
>`OPENFILENAME.lpstrDefExt`: The default extension. [GetOpenFileName](https://docs.microsoft.com/en-us/windows/desktop/api/commdlg/nf-commdlg-getopenfilenamea) and [GetSaveFileName](https://docs.microsoft.com/en-us/windows/desktop/api/commdlg/nf-commdlg-getsavefilenamea) append this extension to the file name **if the user fails to type an extension**."

You can easily test this behaviour with native code like this:
```cpp
#include <wx/wx.h>
#include <commdlg.h>

class MyApp : public wxApp
{
public:
    bool OnInit() override
    {
        WCHAR         fileName[MAX_PATH] = L"test.pdf";
        OPENFILENAMEW ofn{0};

        ofn.lStructSize = sizeof(ofn);     
        ofn.lpstrFilter = L"DXF Files (*.dxf)\0*.dxf\0";
        ofn.lpstrFile   = fileName;
        ofn.nMaxFile    = MAX_PATH;
        ofn.Flags       = OFN_OVERWRITEPROMPT;   
        ofn.lpstrDefExt = L"dxf";

        if ( GetSaveFileNameW(&ofn) )
            wxLogMessage("Selected file '%s'", ofn.lpstrFile);

        return false;
    }
}; wxIMPLEMENT_APP(MyApp);
```
Or just use a built-in application like Notepad to test the scenarios you described and see that when the user provides any extension, the default extension is not appended to the file name.

**Comment by pkhoan** [comment] 2022-02-08 11:35
@PBfordev : Thank you for the examples. It's a good idea to test with other native windows applications.
I don't have any problem with the fact that the default extension is appended to the filename or not, my only concern is the **coherence** in behaviours.

The following applications ONLY append the (first) default extension if the filename has no extension at all, otherwise they used the extension given by user :

**1. Notepad:**
- enter **_test_** --> no extension --> append default extension -- > return **_test.txt_**
- enter **_test.dxf_** (this file does not exist) --> have extension --> return **_test.dxf_**
- enter **_test.pdf_** (this file does exit) -->  have extension --> return **_test.pdf_**

**2. Paint:**
- enter **_test_** --> no extension --> append the first default extension -- > return **_test.png_**
- enter **_test.dxf_** --> have extension --> return **_test.dxf_**
- enter **_test.pdf_** (this file does exit) -->  have extension --> return **_test.pdf_**

The following application ALWAYS append the the (first) default extension if the filename has no extension or the extension given by user isn't the default one:

**1. Microsoft Excel** for Microsoft 365 MSO (Version 2111 Build 16.0.14701.20278) 64-bit:
- enter **_test_** --> no extension --> append default extension -- > return **_test.xlsx_**
- enter **_test.dxf_** (this file does not exist) --> no default extension --> append default extension --> return **_test.dxf.xlsx_**
- enter **_test.pdf_** (this file does exit) --> no default extension --> append default extension --> return **_test.pdf.xlsx_**

**2. Microsoft Word** for Microsoft 365 MSO (Version 2111 Build 16.0.14701.20278) 64-bit:
- enter **_test_** --> no extension --> append default extension -- > return **_test.docx_**
- enter **_test.dxf_** (this file does not exist) --> no default extension --> append default extension --> return **_test.dxf.docx_**
- enter **_test.pdf_** (this file does exit) --> no default extension --> append default extension --> return **_test.pdf.docx_**

For me, the behaviour of the above applications stays coherence in a same application event it isn't necessary the same across different applications.
I would like to see the same coherence in wxFileDialog.

**OS information:**
Windows 10.0.19042.1469

**Comment by PBfordev** [comment] 2022-02-08 12:30
> For me, the behaviour of the above applications stays coherence in a same application event it isn't necessary the same across different applications. For now, wxFileDialog has a mixed behaviour between the two above applications groups. I would like to see the same coherence in wxFileDialog.

AFAIK, wxWidgets mantra is basically "we follow the platform native behaviour". IMO, my example, demonstrating what the underlying Win32 API does is the strong indicator of what should be, or here, rather should not be done. Additionally, your own examples using bundled Windows applications clearly show that if there is already an extension, the default extension should not be appended at the `wxFileDialog` level. 

Of course, a wxWidgets-using application is free to do anything it wants, and just like MS Office, it can find reasonable to ignore the user preference for the extension and force-append its own. Additionally, we do not live in the era of 8.3 names anymore, so it is not simple even to tell whether there already actually is a true file extension. However, I believe this can be done easily at the application level.

As always, one more argument against changing the current behaviour could be maintaining backwards compatibility.

Perhaps it would be interesting to know what is the native behaviour (if there is one) on other platforms such as GTK and MacOS. I am using only Windows, so I have no idea about that.

**Comment by pkhoan** [comment] 2022-02-08 13:27
> EDIT
> I forgot to write one more reason why I believe that appending the default extension should be done at the application, not wxFileDialog, level. For example, in a plain-text editor it makes sense to not force an extension as there are countless file formats using a plain text file and having a different extension (md, cpp, html, rc, svg...). OTOH, an application saving the file in the PNG format may scoff at any extension that is not "png"...

Maybe I haven't made it clear enough that I absolutely have no problem at all if there is no extension appended automatically to the filename (like the behaviour of Notebook, Paint). 

The inconsistence problem of wxFileDialog is:
- if we enter **_test.xyz_** and this file does NOT existe, it returns **_test.xyz.dxf_**
- if we enter **_test.xyz_** and this file DOES existe, it returns **_test.xyz_**

The fact that the extension appending behaviour changes when a file existes or not is quite weird.

I'm interested in the native behaviour of other platforms too but I only use Windows.

**Comment by PBfordev** [comment] 2022-02-08 13:58
Ah, I completely missed the point, sorry. 

I can confirm the difference in the behaviour, i.e., the default extension is appended only when a file with a custom extension does not exist, otherwise the name of the existing file is returned (regardless of `wxFD_OVERWRITE_PROMPT` ).

While the exactly same behaviour can be observed when using the native `GetSaveFileName()` (see my first code block in my first post in this issue), I do agree that this behaviour may be unexpected.

**Comment by pkhoan** [comment] 2022-02-08 15:51
> While the exactly same behaviour can be observed when using the native GetSaveFileName() (see my first code block in my first post in this issue) as well as in Notepad, I do agree that this behaviour may be unexpected.

In Notepad on Windows 10.0.19042.1469, I don't find the same inconsistence behaviour. Notepad doesn't append the default extension to a filename which has already an extension, redargless of its existence:

> 1. Notepad:
> - enter **_test_** --> no extension --> append default extension --> return **_test.txt_**
> - enter **_test.dxf_** (this file does not exist) --> have extension --> return **_test.dxf_**
> - enter **_test.pdf_** (this file does exist) --> have extension --> return **_test.pdf_**

**Comment by PBfordev** [comment] 2022-02-08 16:14
> In Notepad on Windows 10.0.19042.1469, I don't find the same inconsistence behaviour. Notepad doesn't append the default extension to a filename which has already an extension, redargless of its existence:

You are correct. However, surprisingly, I was correct as well.

It seems it also depends on the custom extension. In my previous test I used the same extension you mentioned: "xyz". When this extension is used (not associated with any application on my PC), i.e., the file name entered is "test.xyz" and file "test.xyz" does not exist; the default extension is added by `GetSaveFileName()` as well as Notepad, i.e., the file is saved as "test.xyz.txt". 

When I use "dxf" and "pdf" (both have applications associated) instead of "xyz", I see the same you did, i.e., the default extension is not added, regardless of file existence.

**Comment by pkhoan** [comment] 2022-02-08 16:29
Ah ha, you are right, so Notepad identifies an extension by the file association list in windows, not by the conventional dot format. But at least, there's a logic though it's not evident.

**Comment by PBfordev** [comment] 2022-02-08 18:12
> ... so Notepad identifies an extension by the file association list in windows...

As I wrote, I believe that is the innate behaviour of the Win32 API (`GetSaveFileName()`). Notepad (WordPad, Paint,  Snip & Sketch...) just takes the file name from there. Hence, the same behaviour should be observed when using `wxFileDialog` (not saying it is unsurprising).

MS Word (tested with v2201) behaves differently but it seems to use heavily customized `IFileDialog`, even providing a custom action dialog when the file exists.

**Comment by vadz** [comment] 2022-02-08 19:42
Sorry, I didn't read everything here, but I totally agree with what @PBfordev says and I don't think there is any bug here at all, so closing.

**Closed by vadz** 2022-02-08 19:42 UTC
Labels: MSW, repro needed

**Comment by pkhoan** [comment] 2022-02-09 00:31
@vadz : Sorry but I get confused here. I don't think @PBfordev meant the behaviour of wxFileDialog is normal. He said "the same behaviour **should** be observed when using wxFileDialog" but this isn't the case.

Let me resume the inconsistence of wxFileDialog behaviour here:

wxFileDialog **should** have the following behaviour (like Notepad, Paint... or `GetSaveFileName()`):
`wxFileDialog(this, _("DXF File"), "", "", "DXF file (*.dxf)|*.dxf", wxFD_SAVE).GetPath()` 
return **_test.pdf_** if we enter **_test.pdf_**, regardless of whether this file **exists or not**

Howerver, the **actual** behaviour of wxFileDialog is different:
`wxFileDialog(this, _("DXF File"), "", "", "DXF file (*.dxf)|*.dxf", wxFD_SAVE).GetPath()` 

- return **_test.pdf_** if we enter **_test.pdf_** and this file **exists**
- return **_test.pdf.dxf_** if we enter **_test.pdf_** and this file does **not exist**

I think @PBfordev [did agree](https://github.com/wxWidgets/wxWidgets/issues/22088#issuecomment-1032638157) with me about that.

**Comment by PBfordev** [comment] 2022-02-09 06:25
> @vadz : Sorry but I get confused here. I don't think @PBfordev meant the behaviour of wxFileDialog is normal. He said "the same behaviour **should** be observed when using wxFileDialog" but this isn't the case.
....
I think @PBfordev [did agree](https://github.com/wxWidgets/wxWidgets/issues/22088#issuecomment-1032638157) with me about that.

I did not agree. I actually do observe `wxFileDialog` having the same behaviour as the native one.

When I run this code
```cpp
#include <wx/wx.h>
#include <wx/filedlg.h>

class MyApp : public wxApp
{
public:
    bool OnInit() override
    {
        wxFileDialog fd(nullptr, "Save file", "", "", "DXF Files (*.dxf)|*.dxf", wxFD_SAVE);

        if ( fd.ShowModal() == wxID_OK )
            wxLogMessage("Selected file '%s'.", fd.GetFilename());

        return false;
    }
}; wxIMPLEMENT_APP(MyApp);
```
enter "test.pdf", and hit OK; `wxFileDialog` always returns just "test.pdf" regardless of this file existence.

`wxFileDialog`'s behaviour for the unregistered file extension ("xyz") is also the same as the native one, i.e., the default extension is appended only when such file (e.g., "test.xyz") does not exist.

**Comment by pkhoan** [comment] 2022-02-09 08:06
@PBfordev : Wow, you are right. 
In the past, I must have tested wxFileDialog with some unassociated extension without paying attention.
@vadz : Now, it's clear. I agree that wxFileDialog behaviour is logical and there's no more issue.
Thank @PBfordev for the examples and the explanations.
