### ISSUE TITLE
Missing helptext in status bar when mouse is above submenu-entry

### ISSUE THREAD

**Issue by BusyHarry** [wxWidgets/wxWidgets#24842] opened 2024-09-27 14:06 UTC
# Description

As the title says, you don't get the help-text in the status bar when the mouse is over a submenu-entry.
All the other menu-entries do show the helptext, so I am not sure if its my error or a problem in the library.

# To Reproduce:

- edit the samples\statbar\statbar.cpp
- add in line 359 a helptext: 'statbarStyleMenu);' --> 'statbarStyleMenu, "help Status bar style");'
- add in line 403 a helptext: 'statbarPaneStyleMenu);' --> 'statbarPaneStyleMenu, "help Field style");'

Btw already in 2009 there was a question about this, but no answers:
"wxMenu::AppendSubMenu help string not displaying"
[viewtopic.php?p=111705#p111705](https://forums.wxwidgets.org/viewtopic.php?p=111705#p111705)

# Platform and version information:
  - wxMSW 
  - wxWidgets v3.2.6 (same in v3.2.4, v3.2.5)
  - Win10

**Comment by vadz** [comment] 2024-09-27 17:39
This is due to Windows not allowing to specify IDs for the submenus (unlike for the normal items) and so not allowing us to easily find the item corresponding to the `WM_MENUSELECT` message we receive. I think it might be possible to implement this as Windows still provides us with the position of the item in the list of them, in the `nItem` argument, so we just need to iterate over all the children of the menu (which we also have, via `hMenu`) to find it. There would be more changes needed, e.g. `wxMenuEvent` would have to carry a `wxMenuItem` instead of, or in addition to, the item ID, but this looks doable and if anybody would like to do it, your PRs would be welcome.

BTW, here is the reproducer in a more useful form (please read [our issue reporting guidelines](https://www.wxwidgets.org/develop/how-to-report-issues/)):

```diff
diff --git a/samples/statbar/statbar.cpp b/samples/statbar/statbar.cpp
index 26d06db1b8..b5732ff5cf 100644
--- a/samples/statbar/statbar.cpp
+++ b/samples/statbar/statbar.cpp
@@ -353,7 +353,7 @@ MyFrame::MyFrame(const wxString& title, const wxPoint& pos, const wxSize& size)
                                       "wxSTB_ELLIPSIZE_END",
                                       "Toggle wxSTB_ELLIPSIZE_END style");
     statbarMenu->Append(StatusBar_SetPaneStyle, "Status bar style",
-                        statbarStyleMenu);
+                        statbarStyleMenu, "Help for status bar style");
     statbarMenu->AppendSeparator();
 
     statbarMenu->Append(StatusBar_SetField, "Set active field &number\tCtrl-N",
```

**Comment by mxdamien** [comment] 2024-10-11 09:21
Hey !

I gave this a shot - Feedback very welcome.

I'm not sure about the implication of removing MF_POPUP from the flags check. Both submenus and the top level window carry this flag. I could not find another way to distinguish between the submenu and the top level menu

**Comment by vadz** [comment] 2024-10-15 13:11
Great, thanks! Merged now.

**Closed by vadz** 2024-10-15 13:11 UTC
Labels: MSW
