### ISSUE TITLE
MSVC C++20 Compile Errors due to `wxSETUPH_PATH_STR`

### ISSUE THREAD

**Issue by k3DW** [wxWidgets/wxWidgets#22654] opened 2022-07-19 22:06 UTC
I built wxWidgets 3.2.0 using `build\msw\wx_vc17.sln` with Visual Studio 17.2.6. I changed the C++ Language Standard to C++20 in all projects for all configurations, otherwise I changed nothing else. The full batch build was successful.

In a new project, with all the header and library directories properly configured, a simple file consisting of just `#include "wx\wx.h"` fails to compile with C++20 but passes with C++17.

```
Warning	C5103	pasting '/' and 'vc_x64_lib' does not result in a valid preprocessing token                         include\msvc\wx\setup.h	142	
Warning	C5103	pasting 'vc_x64_lib' and '/' does not result in a valid preprocessing token                         include\msvc\wx\setup.h	142	
Warning	C5103	pasting '/' and 'msw' does not result in a valid preprocessing token                                include\msvc\wx\setup.h	142	
Warning	C5103	pasting 'mswu' and '/' does not result in a valid preprocessing token                               include\msvc\wx\setup.h	142	
Error	C1083	Cannot open include file: '../../../lib/ vc_x64_lib / mswu /wx/setup.h': No such file or directory  include\msvc\wx\setup.h	142
```

I think this is about stricter preprocessor compliance. A small change in `include\msvc\wx\setup.h` may do the trick.

**Comment by vadz** [comment] 2022-07-19 23:06
I don't have this MSVS version yet, I'll try to upgrade to it and test/find a fix for this, but this is problematic because we're going to have a problem constructing the include paths if we can't concatenate strings with `/` any more.

**Comment by k3DW** [comment] 2022-07-19 23:11
I was able to change line 134 from
`wxCONCAT6(../../../lib/, wxLIB_SUBDIR, /, wxTOOLKIT_PREFIX, wxSUFFIX, /wx/setup.h)`
to
`../../../lib/wxLIB_SUBDIR/wxCONCAT(wxTOOLKIT_PREFIX, wxSUFFIX)/wx/setup.h`
and I think it does the same thing.

**Comment by paulcor** [comment] 2022-07-20 02:06
> I don't have this MSVS version yet

I suspect you may just need to use `-Zc:preprocessor`.

**Comment by SpareSimian** [comment] 2022-07-20 02:45
I'm using Microsoft Visual Studio Community 2019 Version 16.11.15 and it doesn't happen with my x64 project. (I added foo.cpp with your one-liner to my project and don't get an error.)

**Comment by k3DW** [comment] 2022-07-20 04:59
It seems like this only reproduces with `/Zc:preprocessor`, and may not be related directly to the C++ std version.

I don't think I am able to open a pull request in this repo, but I am attaching my suggested change as a diff to `include\msvc\wx\setup.h`. This change works for me.
[diff.txt](https://github.com/wxWidgets/wxWidgets/files/9146641/diff.txt)

**Comment by oneeyeman1** [comment] 2022-07-20 05:22
@k3DW ,

> I don't think I am able to open a pull request in this repo, 

Yes, you need to make your own fork and make a PR through it.

Thank you.

**Comment by SpareSimian** [comment] 2022-07-20 23:53
I extracted the relevant parts of  the wx headers to create a reproducible example and then did a divide-and-conquer to narrow down what's wrong. The most important issue is that you can't use the token-pasting operator (##) to paste dot and slash together to create a path. The result is not a token because those are operators that join separate tokens. 

https://stackoverflow.com/questions/13216423/error-pasting-and-red-does-not-give-a-valid-preprocessing-token

String pasting to build the #include argument isn't portable:

https://stackoverflow.com/questions/39038867/string-concatenation-for-include-path

I found that I could build the string by NOT using the ## token concatenation operator to build the path. Instead, only use that operator to build individual path components, and do the final pasting by simply joining the components with "/":

```
#define wxMAKE_PATH3(component1, component2, component3) component1/component2/component3
#define wxSETUPH_PATH wxMAKE_PATH3(../../../lib, wxLIB_SUBDIR, wx/setup.h)
#define wxSETUPH_PATH_STR wxSTRINGIZE(wxSETUPH_PATH)
#include wxSETUPH_PATH_STR
```

**Comment by vadz** [comment] 2022-07-31 13:46
I've created the PR above based on the patch from @k3DW, please test it (especially with the old MSVC versions) if you can.

**Comment by SpareSimian** [comment] 2022-07-31 18:56
I'm running my script to rebuild debug/release, 32/64, and MSVC versions 2010/2013/2015/2019, using nmake. I injected "CPPFLAGS=/Zc:preprocessor" on the nmake command line. So far no problems from setup.h.

I'm seeing C5105 warnings from winbase.h. The older Win10 SDK I've got installed apparently has issues with the new preprocessor. (It accepts the invalid expressions and does the right thing but issues a warning.) It's since been fixed but I haven't pulled a Visual Studio update in quite some time. I'm guessing that installing VS2022 would pull in the new SDK.  This is just a heads-up that it's _not_ an issue with wx. Details:

https://developercommunity2.visualstudio.com/t/std:c17-generates-warning-compiling-Win/1249671?preview=true

**Comment by SpareSimian** [comment] 2022-07-31 20:22
PR linked with an app and appears to work fine, using VS2019 x64 debug.

**Comment by SpareSimian** [comment] 2022-07-31 20:27
Ignore my previous comment, I seem to not be getting the PR in my checkout, I'm trying to hunt down what I did wrong.

**Comment by SpareSimian** [comment] 2022-07-31 22:06
Ok, using the correct branch, my VS2019 x64 debug code now builds and runs properly with the PR.

**Closed** 2022-08-19 21:50 UTC
Labels: build, backport-3.2

**Comment by k3DW** [comment] 2022-08-21 01:48
Sorry, I tested this out and forgot to reply. Thanks for the help :)
