### ISSUE TITLE
The font looks not clear

### ISSUE THREAD

**Issue by yjmthu** [wxWidgets/wxWidgets#22231] opened 2022-03-25 02:34 UTC
![image](https://user-images.githubusercontent.com/73242138/160042768-36e3056c-d897-4a63-b68b-743555027ac0.png)

I'm using Widows 11 now. When I use wxWidgets to create a window, its font looks not clear on the wxButton, wxStaticText and so on.
But the title of the window has a high quality font. I've tried looking for a solution on the internet but haven't found one. Is it a bug?

**Comment by arjndr** [comment] 2022-03-25 08:06
Most likely not a bug. From what I know, you'll have to use a manifest file and set the "dpiAware" property in the manifest file, see [this](https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process). If you're using CMake here's a sample of how to include a manifest file named `APP.exe.manifest`:

```cmake
add_custom_command(
    TARGET ${APP_NAME}
    POST_BUILD
    COMMAND "mt.exe"
      "-manifest \"${CMAKE_SOURCE_DIR}/src/APP.exe.manifest\""
      "-outputresource:\"${CMAKE_BINARY_DIR}/APP.exe\";1"
)
```

**Comment by vadz** [comment] 2022-03-25 12:25
This is indeed not a bug, your application display is clearly getting pixel-doubled which indicates that your application is not marked as DPI-aware. See [the manual](https://docs.wxwidgets.org/trunk/overview_high_dpi.html#high_dpi_platform_msw) for more details.

**Closed by vadz** 2022-03-25 12:25 UTC
