### ISSUE TITLE
wxGrid deleteRows() not working properly

### ISSUE THREAD

**Issue by roenck** [wxWidgets/wxWidgets#22420] opened 2022-05-11 09:41 UTC
**Describe the bug**
Deletion of whole rows not working as expected for some build-combinations.

**Expected vs observed behaviour**
Delete a row removes it and the line is not shown anymore. Vs deleted lines appear 'darkgray' and not selectable.

**Patch or snippet allowing to reproduce the problem**
Hopefully should occur with a single wxGrid example.

**Platform and version information**
 - wxWidgets version you use: 3.1.5 and Git-Dev (from 2022-05-11)
 - wxWidgets port you use: wxMSW and wxGTK
 - OS and its version: Windows 10 and Ubuntu 20.04
 - For wxGTK only:
   + GTK version: 2.24.32
   + Which GDK backend is used: X11

Important, the issue occurs in combinations of platform and used libs and wx-releases:
---> Linux + wx3.1.5 + GTK2 ---> FAILED
---> Linux + wx3.1.5 + GTK3 ---> OK
---> Linux + wxGIT + GTK3 ---> FAILED
---> Windows + wxGIT + wxMSW --> FAILED

**Comment by PBfordev** [comment] 2022-05-11 11:19
I cannot reproduce using the grid sample, GIT master, and Windows 10.

I selected a row and used "Edit / Delete selected rows" menu command. The behaviour was as expected, i.e., the deleted row disappeared and the rows below it moved up. Tried with one row and with multiple rows with the same result. Tried also with the top row frozen, with row 2 hidden, with non-editable grid: Still the same result.

Is there anything special about your "non-deletable" rows?

**Comment by roenck** [comment] 2022-05-11 17:59
Tried to strip it to a minimal sample (Help -> About call the deleteRows-method).

[MinimalSampleGrid.zip](https://github.com/wxWidgets/wxWidgets/files/8672324/MinimalSampleGrid.zip)

![Grid_1](https://user-images.githubusercontent.com/100382302/167915591-99292f26-c00a-49f7-b91b-3c4301da2d45.png)
![Grid_2](https://user-images.githubusercontent.com/100382302/167915670-2ab49171-5ef2-404e-8ccf-192ee1409277.png)
![Grid_3](https://user-images.githubusercontent.com/100382302/167915686-79898511-419f-47cd-b2fa-3eff518a3983.png)

**Comment by DietmarSchwertberger** [comment] 2022-05-11 19:13
In grid.cpp `wxGrid::Redimension` there is a line:
` for ( rowPos = 0; rowPos < m_numCols; rowPos++ )`
This should be:
` for ( rowPos = 0; rowPos < m_numRows; rowPos++ )`

**Comment by PBfordev** [comment] 2022-05-11 19:35
Odd that I could not reproduce it with the sample (I doublechecked I built the current master with the bug):
![wxgrid-del-rows](https://user-images.githubusercontent.com/12495521/167930991-864e158b-032a-4c77-92b0-870c4a47124f.gif)

**Comment by DietmarSchwertberger** [comment] 2022-05-11 20:13
Oh, seems I introduced this with the support for row re-ordering, when I copied code from the column handling to row ordering.
Sorry for this.

So, with 3.1.6 you should not see the bug.
With the repository version, you can e.g. select more than 900 rows and you'll get an assertion.

But that does not explain why there is an isssue with 3.1.5.

**Comment by DietmarSchwertberger** [comment] 2022-05-11 20:15
@roenck : Thanks for the sample and for testing. Could you please check whether the issue is really there with 'Linux + wx3.1.5 + GTK2 ---> FAILED' ?

**Comment by vadz** [comment] 2022-05-11 21:38
@roenck Please let us know if you can still see the problem with the latest master, i.e. including 2698dde445 (Fix regression in wxGrid::DeleteRows(), 2022-05-11), but I think it should be fixed now.

**Closed** 2022-05-11 21:37 UTC

**Comment by roenck** [comment] 2022-05-11 21:43
The issue with GTK2 was an "accident" some days before. It was not my intention to use this lib, but I tried it with my application and got an equivalent behaviour, next was to roll back to GTK3.

But I'am not 100% sure if it was wx3.1.5, it's possible I twist this with wx3.1.6.
