### ISSUE TITLE
Invalid page index used in wxAuiNotebook

### ISSUE THREAD

**Issue by fcloud2020** [wxWidgets/wxWidgets#24027] opened 2023-11-02 07:49 UTC
When I used Code::Blocks to build a demo of wxAuiNotebook, there was an error and the program crashed. As shown below:
![001](https://github.com/wxWidgets/wxWidgets/assets/70119079/f9985c8a-de0c-4b24-83b5-2e80999d547c)
![002](https://github.com/wxWidgets/wxWidgets/assets/70119079/c0c68a19-92eb-4883-807e-8136c5932af7)
![003](https://github.com/wxWidgets/wxWidgets/assets/70119079/1fe7ceaf-9642-414c-8d44-9978e7d0fdf7)
![004](https://github.com/wxWidgets/wxWidgets/assets/70119079/abd5dc4e-dd64-41f9-8c7d-bccb3710172e)
![005](https://github.com/wxWidgets/wxWidgets/assets/70119079/c2c69f23-1024-4518-a8e0-10cd339b3093)

**Comment by fcloud2020** [comment] 2023-11-03 15:13
development environment: Windows 10 + wxWidgets 3.2.3 + Code::Blocks svn:13373.
![callStack](https://github.com/wxWidgets/wxWidgets/assets/70119079/74ab0446-2f87-41a3-804c-08bcdd16b824)

**Comment by fcloud2020** [comment] 2023-11-03 15:33
This error occurs when holding down the left mouse button in the green marker and dragging through the caption of the page.
![error-repeat](https://github.com/wxWidgets/wxWidgets/assets/70119079/08b313f0-eb60-49c5-babc-661d6ad84d06)

**Comment by fcloud2020** [comment] 2023-11-04 02:27
I think there might be something wrong with the code.
![error-reason](https://github.com/wxWidgets/wxWidgets/assets/70119079/dc094ad6-701c-491f-a797-ee5eb1204cef)

**Comment by vadz** [comment] 2023-11-05 03:07
The trouble is that you're reproducing it in the code which I don't have, so it's hard for me to follow. Could you please check if you can reproduce the problem in the AUI sample included in wxWidgets itself (`samples/aui`) and describe which steps are necessary in order to do it there? TIA!

**Comment by fcloud2020** [comment] 2023-11-05 14:02
![wxAui_1](https://github.com/wxWidgets/wxWidgets/assets/70119079/21845a1b-2c05-4ae8-a614-2672da75aaa4)
![wxAui_2](https://github.com/wxWidgets/wxWidgets/assets/70119079/5b62c831-2b9c-43a3-bd15-9a8c305349cc)

**Comment by vadz** [comment] 2023-11-05 22:42
Thanks for the instructions! I can indeed reproduce this, will debug.

**Comment by vadz** [comment] 2023-11-05 23:15
I've created #24039 with the fix for this bug. If you can test this PR, or just cherry pick the (small) change from its first commit f1a3816cd9da0c3c7ceebe9735d37fb2d3158388 and confirm that you can't reproduce the problem any longer, it would be appreciated. TIA!

**Comment by fcloud2020** [comment] 2023-11-07 14:05
Sorry, I was a little busy yesterday. 
After many tests today, I think this fix is perfect.  This bug is gone with wind. :-)
Thank you for your help and hard work!

**Closed** 2023-11-07 14:12 UTC
