### ISSUE TITLE
Ability to post events to a wxWebview in a frame programmatically.

### ISSUE THREAD

**Issue by deadlocklogic** [wxWidgets/wxWidgets#22233] opened 2022-03-25 23:34 UTC
Hi,
I have a simple interactive (mouse move aware) `wxWebView` inside a `wxFrame` on monitor 1 and I am trying to send events to it without success.
In my case the mouse cursor isn't necessarily inside the frame(could be on monitor 2) but the coordinate are carefully calculated.
I tried:
1. `wxPostEvent`  using a `wxMouseEvent`
2. `PostMessage(handle, WM_MOUSEMOVE, 0, MAKELPARAM(x, y))`

Both are failing: **the webview isn't getting any interaction**.
I tried binding an `wxEVT_MOTION` event handler to the webview, and I noticed that events are getting normally received.
So the webview is getting events but not visually interacting accordingly.

Any thoughts/help is appreciated.
Thanks.

**Platform and version information**
 - wxWidgets version you use: latest
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10

**Comment by vadz** [comment] 2022-03-25 23:42
You can't use `wxPostEvent()` to send any events to the native window by design and using `PostMessage()` like this is probably insufficient because you need to emulate more mouse events. Try using `wxUIActionSimulator` but, generally speaking, what you're trying to do is out of scope of wx API and is not supposed to work.

**Closed by vadz** 2022-03-25 23:42 UTC

**Comment by deadlocklogic** [comment] 2022-03-25 23:48
Thanks for the super quick reply!
Basically what I was trying to do is making a wallpaper application with wxwidgets.
So the webview inside the frame can't receive direct input because it is in the background.
A `wxUIActionSimulator` is pretty much useless for this case (the window is out of reach).
So you think the only way is to use native api?
I thought it is kinda weird because the event is received only programmatically but no visual interaction at all.

**Comment by vadz** [comment] 2022-03-25 23:50
`wxUIActionSimulator` should be able to simulate events for any window, not sure why do you think it's out of reach for it.

But if it doesn't work, you will have to resort to the native API, yes. Native controls, such as `wxWebView`, don't know anything about wx events and so posting them won't do any good.

**Comment by deadlocklogic** [comment] 2022-03-26 00:10
But `wxUIActionSimulator` will change the cursor's position which is undesired + won't work anyway for background windows (windows behind the icons).
Dunno, if I can find any docs about how `wxWebView`'s native events behave maybe my task would be much easier.
Btw I knew that plain `wxEvent` won't work but I was surprised that `PostMessage` won't either, as this is the expected way of passing events on windows (and wxMSW is using it under the hood).
