### ISSUE TITLE
regression: 3.2.5 kicad/gtk plot window is not shown correct.

### ISSUE THREAD

**Issue by yuiiio** [wxWidgets/wxWidgets#24551] opened 2024-05-23 03:12 UTC
correct(3.2.4.1):
![20240523_12h07m04s_grim](https://github.com/wxWidgets/wxWidgets/assets/36093713/d88e3a1e-0b2f-43b4-831f-aaad4da468f1)

bad(3.2.5, can't resize plot window and missing plot button and output message box):
![20240523_12h13m16s_grim](https://github.com/wxWidgets/wxWidgets/assets/36093713/0c9e9099-e63b-40de-9f58-b804ae7b3081)

bisected first bad commit is 
https://github.com/wxWidgets/wxWidgets/commit/70df01dcc478e4793b4e29bdd6cb5c13cd4c4c33
and 3.2.5 with revert this commit seems fix this issue.

**Comment by paulcor** [comment] 2024-05-23 13:13
I can't reproduce a problem with `wxListBox` `GetBestSize()` using this patch to the `minimal` sample:
```diff
diff --git a/samples/minimal/minimal.cpp b/samples/minimal/minimal.cpp
index 5f32257c6b..68d32ec9c5 100644
--- a/samples/minimal/minimal.cpp
+++ b/samples/minimal/minimal.cpp
@@ -188,6 +188,15 @@ void MyFrame::OnQuit(wxCommandEvent& WXUNUSED(event))
 
 void MyFrame::OnAbout(wxCommandEvent& WXUNUSED(event))
 {
+    wxDialog d(this, -1, "d");
+    constexpr unsigned n = 99;
+    wxString a[n];
+    for (unsigned i = 0; i < n; i++)
+        a[i] = wxString::Format("item %u", i);
+    wxListBox* lb = new wxListBox(&d, -1, wxDefaultPosition, wxDefaultSize, n, a);
+    d.SetClientSize(lb->GetBestSize());
+    d.ShowModal();
+    return;
     wxMessageBox(wxString::Format
                  (
                     "Welcome to %s!\n"
```

**Comment by vadz** [comment] 2024-05-23 18:18
Apparently it is the [dialog here](https://github.com/KiCad/kicad-source-mirror/blob/032b5a6d6562206fc66203575fd1209637a9056b/pcbnew/dialogs/dialog_plot.cpp#L87) which is affected by this, but I still can't reproduce the problem even with `wxRearrangeList` and mimicking the code there.

@yuiiio What WM/desktop environment do you use?

**Comment by vadz** [comment] 2024-05-23 21:25
I don't have neither labwc nor weston but before installing them I've realized that a better question to ask would have been: do you see the problem with Paul's patch above in your environment? I.e. could you please build the minimal sample from wxWidgets patched like this and run it? TIA!

**Comment by yuiiio** [comment] 2024-05-23 22:19
not changed behavior with paulcor's patched minimal test between with/without commit 70df01d

**Comment by vadz** [comment] 2024-05-23 22:24
Sorry, just to be certain I understand you correctly: does this mean that

1. You see the same problem with this patch, i.e. it works fine with 3.2.4 but not with 3.2.5
2. Or that this patch doesn't show the problem in your environment neither.

?

**Comment by yuiiio** [comment] 2024-05-23 23:09
sorry not clear. I mean 2.

**Comment by paulcor** [comment] 2024-05-24 01:59
> labwc but also same on weston.

So, Wayland.

**Comment by yuiiio** [comment] 2024-05-24 11:57
I found the problem was that the box on the left was too long vertically, pushing the other elements down and hiding them.
 (this is not a problem specific to wayland, same problem occurs in plasma/x11)
![20240524_20h51m06s_grim](https://github.com/wxWidgets/wxWidgets/assets/36093713/cfd34715-d0a8-44b8-9795-aa293bc3dd1b)

**Comment by vadz** [comment] 2024-05-24 17:42
The listbox is supposed to determine its best i.e. minimum size itself. The linked commit increased the computed height, so it somewhat makes sense that it resulted in this regression, but the problem is that I can't reproduce it in a simple example and I'd have to either try to copy more of KiCad dialog code into the sample to do it or just build KiCad (which is supposed to be non-trivial AFAIK).

I wonder if you could add a printf showing the value of `min` in `wxListBox::DoGetBestSize()`? Maybe you could use some unique name for this listbox (I think it's the one [created here](https://github.com/KiCad/kicad-source-mirror/blob/ecb7cd6b84f87163ba231f39d107b7bd05cb9dfc/pcbnew/dialogs/dialog_plot_base.cpp#L57)) and output it only for this name.

**Comment by paulcor** [comment] 2024-05-24 18:30
I have a theory. Does this fix the problem?
```diff
diff --git a/src/gtk/listbox.cpp b/src/gtk/listbox.cpp
index cebd21ac99..bdc3081872 100644
--- a/src/gtk/listbox.cpp
+++ b/src/gtk/listbox.cpp
@@ -934,9 +934,13 @@ wxSize wxListBox::DoGetBestSize() const
     wxSize size(lbWidth, lbHeight);
 #ifdef __WXGTK3__
     // Ensure size is at least the required minimum
+    int w, h;
+    gtk_widget_get_size_request(m_widget, &w, &h);
+    gtk_widget_set_size_request(m_widget, -1, -1);
     wxSize min;
     gtk_widget_get_preferred_width(m_widget, &min.x, NULL);
     gtk_widget_get_preferred_height_for_width(m_widget, min.x, &min.y, NULL);
+    gtk_widget_set_size_request(m_widget, w, h);
     size.IncTo(min);
 #endif
     return size;
```

**Comment by yuiiio** [comment] 2024-05-24 23:30
vadz thanks, I'll try it later. 
@paulcor your patch seems to fix my issue.

**Comment by dsa-t** [comment] 2024-05-25 00:00
We had to add `wxFIXED_MINSIZE` to work around this.

See: https://gitlab.com/kicad/code/kicad/-/commit/f9a9db650373a504157c112a64698cc838af5d29,
https://gitlab.com/kicad/code/kicad/-/issues/16926

**Comment by vadz** [comment] 2024-05-25 14:05
@dsa-t I still don't quite understand what's going on here, but could you please confirm that applying the patch above and removing `wxFIXED_MINSIZE` workaround work for you?

Also, please report regressions in wx to us, it would be nice to have found this before 3.2.5 release rather than after...

**Comment by paulcor** [comment] 2024-05-25 16:19
Can be reproduced with this patch to the `minimal` sample:
```diff
diff --git a/samples/minimal/minimal.cpp b/samples/minimal/minimal.cpp
index 3d71bd276c..00e0bf924a 100644
--- a/samples/minimal/minimal.cpp
+++ b/samples/minimal/minimal.cpp
@@ -188,6 +188,17 @@ void MyFrame::OnQuit(wxCommandEvent& WXUNUSED(event))
 
 void MyFrame::OnAbout(wxCommandEvent& WXUNUSED(event))
 {
+    wxDialog d(this, -1, "d");
+    constexpr unsigned n = 99;
+    wxString a[n];
+    for (unsigned i = 0; i < n; i++)
+        a[i] = wxString::Format("item %u", i);
+    wxListBox* lb = new wxListBox(&d, -1, wxDefaultPosition, wxDefaultSize, n, a);
+    lb->SetSize(-1, 999);
+    lb->InvalidateBestSize();
+    d.SetClientSize(lb->GetBestSize());
+    d.ShowModal();
+    return;
     wxMessageBox(wxString::Format
                  (
                     "Welcome to %s!\n"
```

**Comment by vadz** [comment] 2024-05-25 17:27
Closing as fix was applied to master and I've added it to 3.2 backports branch too. Thanks!

**Closed by vadz** 2024-05-25 17:27 UTC
Labels: GTK
