### ISSUE TITLE
MSW: wxFontPickerCtrl doesn't fully support hiDPI

### ISSUE THREAD

**Issue by willco007** [wxWidgets/wxWidgets#24121] opened 2023-12-07 18:02 UTC
### Description

On a 4k monitor (scale at 150%, resolution 3840x2160), when using wxFontPickerCtrl to pick the font, the picker window is blurry and controls are sized incorrectly.

#### Bug description:

wxFontPickerCtrl font picker window isn't supporting hiDPI fully.

#### Expected vs observed behaviour:

Expect, crisp font drawing and checkbox controls drawn at the correct size. Observed, font is burry and checkboxes are too small.

#### Stack trace:

n/a

#### Patch or snippet allowing to reproduce the problem:

_fontPicker = new wxFontPickerCtrl(this, wxID_ANY, wxNullFont, wxDefaultPosition, wxDefaultSize, wxFNTP_USE_TEXTCTRL);
_fontPicker->GetPickerCtrl()->SetLabel(_("Select..."));

Press the select button to show the picker window.

#### To Reproduce:

show font picker window, observe results (see screenshot)

<img width="320" alt="image" src="https://github.com/wxWidgets/wxWidgets/assets/4294739/e4e3a4be-227e-4abf-a640-7f06a4a0180c">

### Platform and version information

- wxWidgets version you use: 3.2.1
- wxWidgets port you use: wxMSW
- OS and its version: Windows 11, 22H2

**Comment by MaartenBent** [comment] 2023-12-07 20:17
Hi, this is by design. Because these native win32 dialogs (font, colour, file picker) don't support moving between displays with different DPI. Moving it from 250% to 100% would look like this:
<img width="212" alt="Screenshot 2023-12-07 210734" src="https://github.com/wxWidgets/wxWidgets/assets/8088070/ded0566b-229a-47fa-91f0-380e6ed6225f">

The disadvantage is that it always scales from 100%, even if you only have 1 display. 

I suppose we could add a  `wxSystemOptions`, like `msw.dark-mode`, to disable this behavior. And/or only use it when `wxDisplay::GetCount() > 1`.

The font picker is shown with a system-dpi-aware context in:https://github.com/wxWidgets/wxWidgets/blob/96b5c1419bca0519d32688df7dc681ac5f52a2ae/src/msw/fontdlg.cpp#L95-L96

**Closed** 2024-01-19 02:12 UTC
