### ISSUE TITLE
3.3.0 Windows flickering / slow rendering

### ISSUE THREAD

**Issue by kfsone** [wxWidgets/wxWidgets#23585] opened 2023-06-01 02:36 UTC
It looks like this commit: https://github.com/wxWidgets/wxWidgets/commit/fcc7430610ca202b744df75dc3d7e471a1e8b8a4 doesn't take into account that a lot of things turn WS_EX_COMPOSITED off, such as listctrls and sizers.

After switching from 3.2.0 to 3.3.0 we're seeing a lot of flickering and slow rendering, with wxBG_STYLE_PAINT background style using a wxAutoBufferedPaintDC/wxGCDC.

**Comment by vadz** [comment] 2023-06-01 13:00
I've [replied here](https://github.com/wxWidgets/wxWidgets/commit/fcc7430610ca202b744df75dc3d7e471a1e8b8a4#commitcomment-116005294) before seeing this issue, but let me copy the text here too:

True, I hadn't thought we'd have to turn it off in some pretty common cases. Unfortunately I don't think there is any way to convince `LISTVIEW` to work inside a composited window (which is pretty weird, when you think about it, but apparently this control does some strange internal painting optimizations which don't work in this case), so I guess we're going to need to just revert this commit or at least I don't see anything better to do. If anyone has any ideas, please let me know.

**Comment by kfsone** [comment] 2023-06-01 18:42
Oh and the appearance of two users with the problem wasn't intentional - Tommy and I are both Super Evil (actual company name: Super Evil Mega Corp :))

**Comment by petebannister** [comment] 2023-08-30 14:20
wxAutoBufferedPaintDC can cause very slow rendering if drawing bitmaps with alpha on MSW.  Not sure if this really needs a separate bug report? 
The reason is that the backing store bitmap used by wxAutoBufferedPaintDC is a DDB and not a DIB.  If you draw an alpha bitmap onto the DC then AlphaBlt will use wxAlphaPixelData which when not using a DIB will make a copy of the whole backing store.  It does this for each bitmap draw (can be pretty bad on wxAuiToolBar).
I've worked around it by making my own double buffering solution that uses this:

```
            // Convert to DIB.  This way, if transparent images are drawn then 
            // you do not get a DDB=>DIB=>DDB conversion via temporary
            // expensive resource allocations!
            store.ConvertToDIB();
```
Thats meant I have to derive wxAuiToolBar and re-inplement OnPaint.  Would be nice to be able to avoid doing that.

**Comment by vadz** [comment] 2023-08-31 00:52
@petebannister With which wx version do you see this? In 3.3, `wxAutoBufferedPaintDC` shouldn't do any buffering.

**Comment by petebannister** [comment] 2023-08-31 08:25
Ah ok - in 3.2.2.1

**Comment by vadz** [comment] 2023-08-31 13:18
I've extracted this into a separate issue then as this one is explicitly about 3.3.

OTOH this one might be fixed by now, at least the `wxListCtrl` part should be.

@kfsone Can you provide a simple way to reproduce the problem with flickering?

**Comment by vadz** [comment] 2024-11-20 16:29
I haven't heard anything back since more than a year, and I really can't do much here about some concrete examples of the problem. Please reopen, or open new issues, if you still see something wrong.

**Closed by vadz** 2024-11-20 16:29 UTC
Labels: MSW, regression
