### ISSUE TITLE
Different background of the same wxBitmap in toobar and menu item

### ISSUE THREAD

**Issue by LiMinggang** [wxWidgets/wxWidgets#22669] opened 2022-07-26 11:11 UTC
Building with 3.2, the same wxBitmap has different background in toobar and menu item. The wxBitmap was created from xpm which set   transparent backgroud.
On menu, it has a black background.
![image](https://user-images.githubusercontent.com/4847132/180992146-a39ebd64-647e-48be-933e-b0113541ecf6.png)
On toolbar, it's OK
![2022-07-26 19 08 14](https://user-images.githubusercontent.com/4847132/180992890-62e58e7a-d464-4a17-a384-234399e8e780.png)

Nothing changed in app code

**Comment by vadz** [comment] 2022-07-26 14:32
Can you reproduce this in the menu sample? It already has a call to `SetBitmap()`, it would be great to have a minimal patch to the sample showing the problem.

Also, which platform do you use?

**Comment by PBfordev** [comment] 2022-07-26 14:45
FWIW, I cannot reproduce it on Win10, with sample.xpm file:
![wxmenuitem-bmp-xpm](https://user-images.githubusercontent.com/12495521/181036242-69d82669-652e-4682-82f0-05690a556d30.png)
```diff
diff --git a/samples/menu/menu.cpp b/samples/menu/menu.cpp
index 07886e3a8d..1c93db3cbc 100644
--- a/samples/menu/menu.cpp
+++ b/samples/menu/menu.cpp
@@ -57,9 +57,9 @@
     #define USE_LOG_WINDOW 0
 #endif
 
-#ifndef wxHAS_IMAGES_IN_RESOURCES
+// #ifndef wxHAS_IMAGES_IN_RESOURCES
     #include "../sample.xpm"
-#endif
+// #endif
 
 // ----------------------------------------------------------------------------
 // classes
@@ -558,7 +558,7 @@ MyFrame::MyFrame()
 #if USE_LOG_WINDOW
     wxMenuItem *item = new wxMenuItem(fileMenu, Menu_File_ClearLog,
                                       "Clear &log\tCtrl-L");
-    item->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_DELETE, wxART_MENU));
+    item->SetBitmap(wxBitmap(sample_xpm));
     fileMenu->Append(item);
     fileMenu->AppendSeparator();
 #endif // USE_LOG_WINDOW
```

**Comment by LiMinggang** [comment] 2022-07-28 06:29
I'm using Win 10 + VS 2022 community. Will try it with minimal.

**Comment by LiMinggang** [comment] 2022-07-28 06:29
Did not reproduce the issue. with minimal. Will close the issue.

**Comment by LiMinggang** [comment] 2022-07-28 09:33
Not sure if this is a bug or not. I can reproduce it with minimal by the code snippet below. If I used the wxBitmap directly created by xpm, it's OK but got the issue if I used the image from m_ImageList->GetBitmap
Any idea?
    m_ImageList = new wxImageList(IconWidth, IconHeight);
    m_ImageList->Add(wxBitmap(fileopen_xpm));
    item->SetBitmap(m_ImageList->GetBitmap(0));
    //item->SetBitmap(wxBitmap(fileopen_xpm));
    helpMenu->Append(item);
    //helpMenu->Append(Minimal_About, "&About\tF1", "Show about dialog");

**Comment by LiMinggang** [comment] 2022-07-28 09:35
Not sure if it was because of returning a wxBitmap in stack?

**Comment by LiMinggang** [comment] 2022-07-28 10:27
After trying wxWidgets 3.1.6/3.1.7/3.20, I can sure the bug was introduced in 3.1.7

**Comment by LiMinggang** [comment] 2022-07-28 13:12
Reproduced with sample.xpm which was from wxWidgets with the code below
    m_ImageList = new wxImageList(32, 32);
    m_ImageList->Add(wxBitmap(sample_xpm));

    item->SetBitmap(m_ImageList->GetBitmap(0));
    helpMenu->Append(item);

![image](https://user-images.githubusercontent.com/4847132/181513472-fda490a9-c2e6-43a2-96fc-6bba7e30d6da.png)

**Comment by PBfordev** [comment] 2022-07-28 17:45
I can confirm the issue with this
```diff
diff --git a/samples/menu/menu.cpp b/samples/menu/menu.cpp
index 07886e3a8d..a0308ddb74 100644
--- a/samples/menu/menu.cpp
+++ b/samples/menu/menu.cpp
@@ -57,9 +57,9 @@
     #define USE_LOG_WINDOW 0
 #endif
 
-#ifndef wxHAS_IMAGES_IN_RESOURCES
+
     #include "../sample.xpm"
-#endif
+
 
 // ----------------------------------------------------------------------------
 // classes
@@ -558,7 +558,12 @@ MyFrame::MyFrame()
 #if USE_LOG_WINDOW
     wxMenuItem *item = new wxMenuItem(fileMenu, Menu_File_ClearLog,
                                       "Clear &log\tCtrl-L");
-    item->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_DELETE, wxART_MENU));
+
+    wxImageList imageList(32, 32);
+
+    imageList.Add(wxBitmap(sample_xpm));
+    item->SetBitmap(imageList.GetBitmap(0));
+
     fileMenu->Append(item);
     fileMenu->AppendSeparator();
 #endif // USE_LOG_WINDOW
```
The transparency is correct when using `GetIcon()` instead of ` GetBitmap()` , i.e., `item->SetBitmap(imageList.GetIcon(0))`;

**Comment by vadz** [comment] 2022-07-31 13:20
I finally have a solution for this, see the PR linked above, but, as I wrote there, I still don't really understand what's wrong with the current code, which is a bit annoying.

Please test the fix (you can cherry pick just the first commit, i.e. basically just add `32` to `wxBitmap` ctor in `wxImageList::GetBitmap()`) and let me know if you still see any problems with it. TIA!

**Comment by LiMinggang** [comment] 2022-08-01 09:03
Veirified and confirmed the fix. Thanks!

**Comment by a-wi** [comment] 2022-08-01 15:28
It seems there is no problem with `wxImageList` but menu item bitmaps just need to be premultiplied ARGB DIBs - see comment [menuitem.cpp#L697](https://github.com/wxWidgets/wxWidgets/blob/667c5c843b89ed46e3a64242f94487866cb8c3be/src/msw/menuitem.cpp#L697).
So bitmaps returned by `wxImageList::GetBitmap()` have to be converted to DIBs only for menu items and there is no need to always return DIBs from this function (#22679).
Using `wxBitamp::ConvertToDIB()` seems to work:
```diff --git a/src/msw/menuitem.cpp b/src/msw/menuitem.cpp
--- a/src/msw/menuitem.cpp
+++ b/src/msw/menuitem.cpp
@@ -691,15 +691,22 @@ void wxMenuItem::SetItemLabel(const wxString& txt)
 wxBitmap wxMenuItem::GetBitmap(bool bChecked) const
 {
     wxBitmap bmp = GetBitmapFromBundle(bChecked ? m_bitmap : m_bmpUnchecked);
-#if wxUSE_IMAGE
-    if ( bmp.IsOk() && !bmp.HasAlpha() && wxGetWinVersion() >= wxWinVersion_Vista)
+    if (bmp.IsOk() && wxGetWinVersion() >= wxWinVersion_Vista )
     {
         // we must use PARGB DIB for the menu bitmaps so ensure that we do
-        wxImage img(bmp.ConvertToImage());
-        img.InitAlpha();
-        bmp = wxBitmap(img);
-    }
+#if wxUSE_IMAGE
+        if ( !bmp.HasAlpha() )
+        {
+            wxImage img(bmp.ConvertToImage());
+            img.InitAlpha();
+            bmp = wxBitmap(img);
+        }
+        else
 #endif // wxUSE_IMAGE
+        {
+            bmp.ConvertToDIB();
+        }
+    }
     return bmp;
 }

```

**Comment by vadz** [comment] 2022-08-01 15:41
Thanks, I haven't tested it yet, but I'm pretty sure you're right, I've tried tweaking the code here, but I didn't think that the menus might require using DIBs and not support DDBs at all -- in spite of writing the comment you refer to myself back in a5d85ef032 (don't make the items owner drawn unnecessarily under recent Windows systems; fix handling of checked/unchecked bitmaps under Vista too; simplify the code by refactoring bitmaps handling in a separate function, 2009-03-23). 

This would definitely explain the behaviour I was seeing and this is indeed a better fix (if only because DDBs could come from somewhere else too, not just from `wxImageList`).

Whether or not we want to return them from `wxImageList` is still not totally clear, however: considering that image lists are used only for small bitmaps and with the other native APIs, perhaps it would still make sense to do it?

**Comment by vadz** [comment] 2022-08-01 16:46
I did test it now and it works for me, so I've just pushed this change directly because, unlike the previous one, I have no doubts about it, thanks again @a-wi!

This will still have to be backported to 3.2 before closing it.

**Closed** 2022-08-19 21:50 UTC
Labels: MSW, regression, backport-3.2
