### ISSUE TITLE
Repainting `wxGLCanvas` from `wxEVT_IDLE` doesn't work in 3.2.3

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#23996] opened 2023-10-25 00:02 UTC
I took a quick look at why even with the crash fix from #23968, on wxWidgets 3.2.3 moving the mouse inside the video display in Aegisub (which is supposed to render a crosshair centered at the mouse position) is very sluggish.

It turns out that Aegisub does not render the canvas on `wxEVT_PAINT`, but *only* on `wxEVT_IDLE`. But due to the changes from #23554, most attempts to draw on `wxEVT_IDLE` end up doing nothing (due to the flag `m_readyToDraw` being set to false at the time the idle event comes). This test application shows a big difference in fluidity between wxWidgets 3.2.2 and 3.2.3:

```c++
#include <wx/app.h>
#include <wx/glcanvas.h>
#include <wx/dcclient.h>
#include <wx/frame.h>
#include <wx/button.h>
#include <wx/sizer.h>

class MyWxApp : public wxApp
{
	double normX = 0.5;

public:
	bool OnInit() override {
		auto window = new wxFrame(nullptr, -1, wxT("Test"));
		auto canvas = new wxGLCanvas(window);
		auto context = new wxGLContext(canvas);
		canvas->Bind(wxEVT_IDLE, [this, canvas, context](wxIdleEvent &evt) {
			fprintf(stderr, "Canvas paint\n");
			context->SetCurrent(*canvas);

			glClearColor(normX, 0.0f, 0.0f, 1.0f);
			glClear(GL_COLOR_BUFFER_BIT);

			canvas->SwapBuffers();
		});

		canvas->Bind(wxEVT_MOTION, [this, canvas](wxMouseEvent &evt) {
			fprintf(stderr, "Mouse move\n");
			normX = (double)evt.GetPosition().x / canvas->GetSize().GetWidth();
		});

		window->Layout();
		window->Show(true);
		SetTopWindow(window);
		return true;
	}
};

IMPLEMENT_APP(MyWxApp)
```

_Originally posted by @joanbm in https://github.com/wxWidgets/wxWidgets/issues/23961#issuecomment-1776209016_

**Comment by vadz** [comment] 2023-10-25 00:15
I definitely see the problem, thanks.

> does not render the canvas on `wxEVT_PAINT`, but only on `wxEVT_IDLE`.

This is, of course, was always a bad thing to do, any window *must* repaint itself when it gets `wxEVT_PAINT` and IMO it's a real miracle that it worked before. But it's still not nice to change the behaviour like this in a micro release in a stable branch. It's also not very nice that the program still works with X11 but not with Wayland, so I'd like to fix it.

Thinking about it for a bit, it seems that just doing this:

```diff
diff --git a/src/unix/glegl.cpp b/src/unix/glegl.cpp
index 1e404aa790..7357d7c510 100644
--- a/src/unix/glegl.cpp
+++ b/src/unix/glegl.cpp
@@ -826,6 +826,7 @@ bool wxGLCanvasEGL::SwapBuffers()
         if ( !m_readyToDraw )
         {
             wxLogTrace(TRACE_EGL, "Not ready to draw yet");
+            Refresh();
             return false;
         }
 
```
should do it and it indeed does for the example above. Do you see any problems with doing it? I think I've convinced myself that this is not going to result in an infinite repaint loop, but it's too easy to convince oneself... Also, I didn't test it with Aegisub itself, if it's not too much to ask, could you please check if it works there?

I'd also welcome any comments from Aegisub developers if any of them are reading this (@wangqr perhaps?).

**Comment by dgud** [comment] 2023-10-25 13:46
I do all rendering in Wings3D in idle mode as well, normally opengl program are written that way. 
Tested on my wsl ubuntu-23 (which is only way I have wayland) and yes, 
even rotating the camera doesn't work with wayland and wxWidgets-3.2.3. 

The patch works for me, limited testing, though I don't understand why it is NOT causing an eternal redraw loop for me.

**Comment by vadz** [comment] 2023-10-25 14:35
> though I don't understand why it is NOT causing an eternal redraw loop for me.

The way I see it, multiple refreshes coalesce, so any number of them will result just in a single repaint later. And when the repaint does happen, the next idle event handler will be able to swap buffers, so it won't refresh it again.

But, as I said, I found it was pretty easy for me to convince myself, so it's perfectly possible that this is actually wrong.

**Comment by dgud** [comment] 2023-10-25 15:05
Ok read the code better, but does that mean that every repaint will look like this?

1. Get a asynchronous repaint event ( or mouse motion event most often in my case) 
2. Render everything which is a lot of opengl calls (and end with swap buffers)
3. SwapBuffers triggers a refresh event
4. Back to step 1, but with a successful SwapBuffers.

Anyway it this works and wxW-3.2.3 doesn't so an improvement, 
it is hard to notice if it is slower than before, when I only have wsl ubuntu to test with. 
Comparing with windows it runs a bit slower but who knows what that depends on.

**Comment by vadz** [comment] 2023-10-25 15:24
Yes, any OpenGL calls done while the buffers can't be swapped will be wasted. But I don't see how can this be avoided if you don't draw in `wxEVT_PAINT` handler.

I admit that I'm _very_ surprised that it's apparently common practice to do things like this because this goes directly against the basic principle of all the classic UI systems.

**Comment by vadz** [comment] 2023-10-25 15:34
P.S. I don't see how can this be avoided without changing the application code. If you can change it and add `Refresh()` to it yourself, it should work fine.

**Comment by joanbm** [comment] 2023-10-25 19:14
The fix in #23998 fixes my original test case, but does not fix the Aegisub sluggishness. The problem is that Aegisub, inside the `wxEVT_IDLE` handler, does something like `if (!canvas->IsShownOnScreen()) return;`. This `IsShownOnScreen()` method seems broken on Wayland as pointed to in this comment: https://github.com/wxWidgets/wxWidgets/pull/23554#issuecomment-1688358313, so that should be fixed as well. Anyway, the consequence is that it never ends up calling the `SwapBuffers()` function where the change is.

Here's an updated test case that is still affected by the regression:

```c++
#include <wx/app.h>
#include <wx/glcanvas.h>
#include <wx/dcclient.h>
#include <wx/frame.h>
#include <wx/button.h>
#include <wx/sizer.h>

class MyWxApp : public wxApp
{
	double normX = 0.5;

public:
	bool OnInit() override {
		auto window = new wxFrame(nullptr, -1, wxT("Test"));
		auto canvas = new wxGLCanvas(window);
		auto context = new wxGLContext(canvas);
		canvas->Bind(wxEVT_IDLE, [this, canvas, context](wxIdleEvent &evt) {
			// !!!!!!! THIS LINE BELOW IS NEW
			if (!canvas->IsShownOnScreen()) return;
			// !!!!!!! THIS LINE ABOVE IS NEW

			fprintf(stderr, "Canvas paint\n");
			context->SetCurrent(*canvas);

			glClearColor(normX, 0.0f, 0.0f, 1.0f);
			glClear(GL_COLOR_BUFFER_BIT);

			canvas->SwapBuffers();
		});

		canvas->Bind(wxEVT_MOTION, [this, canvas](wxMouseEvent &evt) {
			fprintf(stderr, "Mouse move\n");
			normX = (double)evt.GetPosition().x / canvas->GetSize().GetWidth();
		});

		window->Layout();
		window->Show(true);
		SetTopWindow(window);
		return true;
	}
};

IMPLEMENT_APP(MyWxApp)
```

**Comment by joanbm** [comment] 2023-10-25 20:17
> Yes, any OpenGL calls done while the buffers can't be swapped will be wasted. But I don't see how can this be avoided if you don't draw in `wxEVT_PAINT` handler.

If I understand correctly, technically calling `eglSwapBuffers()` outside `wxEVT_PAINT` / Wayland frame callback works fine, the only problem is that if you don't synchronize yourself with the frame callback, you are potentially wasting resources by drawing faster than your display can show.

As I understand the current approach with #23998 'detects' when the application tries to draw outside of the frame callback, and if so ignores the call and schedules another redraw at a later time.

IIRC `eglSwapBuffers()` by default does something similar (blocks until the next frame callback) but we disabled it for 3.2.3 in #23554 by calling `eglSwapInterval(display, 0);`.

Personally I don't like the "second-guessing" logic inside `wxEGLCanvas::SwapBuffers` in both #23554 and #23998 (my view it should just call `eglSwapBuffers` unless the canvas is still initializing) but I'm not sure how to get rid of it while no reintroducing the performance issue fixed in #23554.

**Comment by vadz** [comment] 2023-10-25 21:39
There is, of course, a problem with `IsShownOnScreen()` in 3.2, thanks for pointing it out, we need to backport cf44a87ec6 (Fix wxGLCanvasEGL::IsShownOnScreen() under Wayland, 2023-09-25) there to fix it (see #23899). With this fix, the updated example works correctly for me too.

As for the rest, there is a crucial difference between refreshing and returning to the event loop and blocking, as `eglSwapBuffers()` does (actually blocking happens in some other function, I forgot in which one), preventing the program from doing anything else, such as redrawing its other windows or processing input or whatever -- and it can block for up to one second currently when the window is fully obscured and it used to block _forever_ in this case, hanging the program completely. We really can't let this happen, at least as long as we can't detect this case ourselves, and I don't think we can.

It's really tragic, if you think about it, Wayland developers wanted to make things more efficient, so now, after spending a lot of time on this (and I'm speaking not about us only, but dozens, if not hundreds, of other projects that ran into the same issue) we might finally have a solution which will be much less efficient than what we had had at the beginning.

**Comment by joanbm** [comment] 2023-10-26 20:52
> There is, of course, a problem with `IsShownOnScreen()` in 3.2, thanks for pointing it out, we need to backport [cf44a87](https://github.com/wxWidgets/wxWidgets/commit/cf44a87ec62f9cefb428b8d6c002c2ee342dc4ec) (Fix wxGLCanvasEGL::IsShownOnScreen() under Wayland, 2023-09-25) there to fix it (see #23899). With this fix, the updated example works correctly for me too.

Yes, I was testing with just 3.2.3 with #23998 on top of it. If I also include #23899, Aegisub works fine.

PS: Something I noticed while testing on Wayland by drawing a crosshair like Aegisub does, is that on wxWidgets v3.2.2, drawing on `wxEVT_IDLE` appears to result in a better framerate than `wxEVT_PAINT` (like `wxEVT_IDLE` is 60fps while `wxEVT_PAINT` is 20fps or something like this), whereas on v3.2.3+#23998+#23899 the opposite happens. My guess is that the improvement in `wxEVT_PAINT` is due to the `eglSwapInterval` change and the regression in `wxEVT_IDLE` is due to the way it's handled since #23899. Either way, that's an improvement for most apps so I wouldn't worry about it much for now.

> > I admit that I'm very surprised that it's apparently common practice to do things like this because this goes directly against the
> > basic principle of all the classic UI systems.
> 
> I used SDL before I ported wxWidgets to erlang. So that is what I come from.
> 
> Most OpenGL examples (at least 20 years ago :-) ) used _SDL_ or _fltk_ or something else simple as a toolkit library, they are all message based instead of callback based.

When I was getting started with OpenGL *many* years ago I also remember seeing a few examples with GLUT that registered a callback inside `glutIdleFunc` that did the drawing. Not sure how good of a practice that was back then or nowadays.

**Comment by Manolo-ES** [comment] 2023-10-27 19:41
As I told in another issue, this seems to me unrelated to wxWidgets.

Drawing from EVT_PAINT seems logical: this is the explicit case where the OS asks for it.
Drawing from EVT_IDLE sounds good because everything else needed before drawing is already done.

From OpenGL point of view, it doesn't matter at all where you draw from. It only matters when you call `SwapBuffers`.
Some people use a thread just for OGL commands, on the hope that the GUI will not block. Well, it may be or not, depending on if the GPU driver can cope with large amount of data and commands.

> Yes, any OpenGL calls done while the buffers can't be swapped will be wasted

Err... only commands that affect the front buffer (as updated by `SwapBuffers`). The rest will be queued and processed, although they can be dismissed if some draw command is called at the wrong time.

**Comment by vadz** [comment] 2023-10-28 16:56
> As I told in another issue, this seems to me unrelated to wxWidgets.

I don't understand this comment at all, are you sure to have understood the issue? It worked with previous version of wx and doesn't work with the latest one, how can it be anything but related to wx?

**Closed** 2023-10-29 00:55 UTC
