### ISSUE TITLE
wxEVT_ENTER_WINDOW / wxEVT_LEAVE_WINDOW not generated for wxSearchCtrl on GTK

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#24245] opened 2024-01-24 17:58 UTC
Modify widgets sample like this:
```patch
diff --git a/samples/widgets/searchctrl.cpp b/samples/widgets/searchctrl.cpp
index 38c98211d5..1bfc5a44e5 100644
--- a/samples/widgets/searchctrl.cpp
+++ b/samples/widgets/searchctrl.cpp
@@ -88,6 +88,10 @@ protected:
     void OnSearch(wxCommandEvent& event);
     void OnSearchCancel(wxCommandEvent& event);
 
+    void onQueryMotion( wxMouseEvent& aEvent );
+    void onQueryMouseEnter( wxMouseEvent& aEvent );
+    void onQueryMouseLeave( wxMouseEvent& aEvent );
+
     wxMenu* CreateTestMenu();
 
     // (re)create the control
@@ -178,6 +182,27 @@ void SearchCtrlWidgetsPage::CreateControl()
 
     m_srchCtrl = new wxSearchCtrl(this, -1, wxEmptyString, wxDefaultPosition,
                                   FromDIP(wxSize(150, -1)), style);
+
+    m_srchCtrl->Bind( wxEVT_MOTION, &SearchCtrlWidgetsPage::onQueryMotion, this );
+    m_srchCtrl->Bind( wxEVT_ENTER_WINDOW, &SearchCtrlWidgetsPage::onQueryMouseEnter, this );
+    m_srchCtrl->Bind( wxEVT_LEAVE_WINDOW, &SearchCtrlWidgetsPage::onQueryMouseLeave, this );
+}
+
+void SearchCtrlWidgetsPage::onQueryMotion( wxMouseEvent& aEvent )
+{
+    std::cout << "onQueryMotion" << aEvent.GetX() << ", " << aEvent.GetY() << std::endl;
+}
+
+void SearchCtrlWidgetsPage::onQueryMouseEnter( wxMouseEvent& aEvent )
+{
+    std::cout << "onQueryMouseEnter" << std::endl;
+    SetCursor( wxCURSOR_IBEAM );
+}
+
+void SearchCtrlWidgetsPage::onQueryMouseLeave( wxMouseEvent& aEvent )
+{
+    std::cout << "onQueryMouseLeave" << std::endl;
+    SetCursor( wxCURSOR_ARROW );
 }
 
 void SearchCtrlWidgetsPage::RecreateWidget()
```

`onQueryMouseEnter`/`onQueryMouseLeave` are never called for wxSearchCtrl.
And `onQueryMotion` is not being called if the cursor is inside the "inner" text field.

---

wxTextCtrl also (probably) has a bug: enter/leave events are based on the "inner" text field. The mouse motion event is still called from outside the "inner" field, but inside the widget borders.

```patch
diff --git a/samples/widgets/textctrl.cpp b/samples/widgets/textctrl.cpp
index 606cf7fc82..830be77944 100644
--- a/samples/widgets/textctrl.cpp
+++ b/samples/widgets/textctrl.cpp
@@ -196,6 +196,10 @@ protected:
 
     void OnIdle(wxIdleEvent& event);
 
+    void onQueryMotion( wxMouseEvent& aEvent );
+    void onQueryMouseEnter( wxMouseEvent& aEvent );
+    void onQueryMouseLeave( wxMouseEvent& aEvent );
+
     // reset the textctrl parameters
     void Reset();
 
@@ -408,6 +412,24 @@ TextWidgetsPage::TextWidgetsPage(WidgetsBookCtrl *book, wxImageList *imaglist)
     m_selTo = -2; // not -1 which means "no selection"
 }
 
+void TextWidgetsPage::onQueryMotion( wxMouseEvent& aEvent )
+{
+    std::cout << "onQueryMotion" << aEvent.GetX() << ", " << aEvent.GetY() << std::endl;
+}
+
+void TextWidgetsPage::onQueryMouseEnter( wxMouseEvent& aEvent )
+{
+    std::cout << "onQueryMouseEnter" << std::endl;
+    SetCursor( wxCURSOR_IBEAM );
+}
+
+void TextWidgetsPage::onQueryMouseLeave( wxMouseEvent& aEvent )
+{
+    std::cout << "onQueryMouseLeave" << std::endl;
+    SetCursor( wxCURSOR_ARROW );
+}
+
+
 void TextWidgetsPage::CreateContent()
 {
     // left pane
@@ -612,6 +634,10 @@ void TextWidgetsPage::CreateContent()
     CreateText();
     m_sizerText->SetMinSize(150, 0);
 
+    m_textLineLast->Bind( wxEVT_MOTION, &TextWidgetsPage::onQueryMotion, this );
+    m_textLineLast->Bind( wxEVT_ENTER_WINDOW, &TextWidgetsPage::onQueryMouseEnter, this );
+    m_textLineLast->Bind( wxEVT_LEAVE_WINDOW, &TextWidgetsPage::onQueryMouseLeave, this );
+
     // the 3 panes panes compose the upper part of the window
     wxSizer *sizerTop = new wxBoxSizer(wxHORIZONTAL);
     sizerTop->Add(sizerLeft, 0, wxGROW | (wxALL & ~wxLEFT), 10);
```

### Platform and version information

- wxWidgets version  you use: 3.3
- wxWidgets port  you use: wxGTK
- OS  and its version: Linux Mint 21.1
  
  + GTK version: 3.24.33-1ubuntu2
  + Which GDK  backend is used: X11
  + Desktop environment : XFCE
  + Current theme:  Mint-Y-Aqua

**Comment by dsa-t** [comment] 2024-01-24 19:39
It doesn't work terribly well on wxMSW as well. 
`wxEVT_LEAVE_WINDOW` is only generated when crossing the thin border, or the search/cancel buttons.
`wxEVT_MOTION` doesn't get generated inside the "inner" field.

**Comment by AliKet** [comment] 2024-01-24 20:03
A quick test shows that the handlers at the **GTK 3** level are correctly called!!
https://github.com/wxWidgets/wxWidgets/blob/ac3cea5bcd5a3fc3d52648efb4dceacbcc9d0698/src/gtk/window.cpp#L2250-L2254

https://github.com/wxWidgets/wxWidgets/blob/ac3cea5bcd5a3fc3d52648efb4dceacbcc9d0698/src/gtk/window.cpp#L2273-L2277

**GTK 2** seems to work correctly though.

**Comment by dizcza** [comment] 2024-02-09 09:19
I have a similar issue with wxEVT_ENTER_WINDOW events not captured on a wxChoice under GTK:
```
      wxString myChoices[] = { wxT("Choice1") };
      wxChoice* choice = new wxChoice( panel, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, myChoices);
      choice->Bind(wxEVT_ENTER_WINDOW, [&](wxMouseEvent& event) {
        wxLogDebug("Enter Window2");
      });
```
The message is never printed, although the callback gets triggered for other UI elements (tried buttons and check buttons).

Originally discussed at https://forums.wxwidgets.org/viewtopic.php?f=1&t=51065.

----

> A quick test shows that the handlers at the GTK 3 level are correctly called!!
> GTK 2 seems to work correctly though.

This means that both GTKs work fine, don't they?

**Comment by vadz** [comment] 2024-02-09 15:47
@dsa-t Is this something affecting KiCad? I'd prioritize this if it does.

**Comment by dsa-t** [comment] 2024-02-09 15:51
> Is this something affecting KiCad? I'd prioritize this if it does

For wxSearchCtrl, yes, see https://gitlab.com/kicad/code/kicad/-/blob/3d690da30511d92619219d18b6154ef57cb4d5de/common/widgets/lib_tree.cpp#L131

**Comment by vadz** [comment] 2024-02-09 18:36
I don't have a fix yet, but the reason for the problem is quite simple: we check that we get event for one of our own `GdkWindow`s, but `GtkSearchEntry` and many (most?) other GTK controls actually have multiple windows associated with them and we don't get the event for the main window, but one of its children and so we just ignore it due to `GTKIsOwnWindow()` returning `false`.

One way of fixing this would be to define `GTKGetWindow()` to actually return all windows used by the control. This would be best because sometimes we need not just to check if the window is ours, but to iterate over all of them in order to do something, e.g. update the cursor.

But this risks being non-trivial (e.g. I don't see how to get `text_area` window from `GtkEntry`) and so for now we could just change `GTKIsOwnWindow()` to check whether any unknown windows are actually children of the main window (by using `gdk_window_get_parent()` until we find the main window or exhaust the parent chain). I don't think this would break anything, but I could be wrong.

@paulcor Please let me know if you see any better way to do this before I do it wrongly, if you see one. TIA!

**Comment by vadz** [comment] 2024-02-09 18:37
As for the problem with `wxChoice`, it's quite different, as there we do _not_ get GTK events in the first place. I suspect (but, again, didn't have time to check it yet) that we need to connect to the signals for the choice children in order to get them.

**Comment by vadz** [comment] 2024-02-10 13:34
Thanks for the search control fix, but this still leaves many other controls with the same problem (notably `wxTextEntry`, which uses `GtkEntry` too) and I can't help wondering: why do we actually check the `GdkWindow` at all? Can we really get this event for any window that is _not_ part of the widget?

This code was there since always, or close to, see its initial appearance in 401ec7b639 (event/leave events scrollbar fix listctrl fix, 1998-07-11), so it was originally added for GTK 1 and I'm not sure at all if it's still relevant for GTK 3 (or even 2).

I don't see any immediate problems after applying this:

```diff
diff --git a/src/gtk/window.cpp b/src/gtk/window.cpp
index a43f5df453..e49b4d0397 100644
--- a/src/gtk/window.cpp
+++ b/src/gtk/window.cpp
@@ -1676,9 +1676,6 @@ int wxWindowGTK::GTKCallbackCommonPrologue(GdkEventAny *event) const
     if (g_blockEventsOnScroll)
         return TRUE;
 
-    if (!GTKIsOwnWindow(event->window))
-        return FALSE;
-
     return -1;
 }
```
and it does result in generating the expected events for many more controls (although still not `wxChoice`, nor the icon zone of `wxSearchCtrl`).

Does anybody see any reason not to do this, at least for the enter/leave events?

**Comment by vadz** [comment] 2024-02-10 15:03
After an embarrassingly looong debugging session I also understand now why we're not getting events when the mouse enters the search control in the icon zone: this is due to this piece of 
`gtk_entry_event()`, which is called for all events happening for `GtkEntry`, including `GDK_ENTER_NOTIFY`:

https://github.com/GNOME/gtk/blob/3e6fd55ee00d4209ce2f2af292829e4d6f674adc/gtk/gtkentry.c#L4338-L4339

AFAICS there is no way to get notified about `GDK_ENTER_NOTIFY` other than defining our own handler for the `event` signal and checking for this event in it first, before `GtkEntry` just drops it on the floor.

As usual, any corrections/better ideas would be welcome!

**Comment by vadz** [comment] 2024-02-18 23:44
As nobody told me that I was on a completely wrong track, I've created #24339 with the proposed fixes. Please test it, TIA!

**Comment by vadz** [comment] 2024-02-29 02:37
I think this should be fixed now, please reopen if you still see any problems.

**Closed by vadz** 2024-02-29 02:37 UTC
Labels: GTK

**Comment by vadz** [comment] 2025-03-08 17:15
FYI, I've added this commit to the 3.2 proposed backports PR too now, please see #25216.
