### ISSUE TITLE
Static text in bold is truncated on the wizard page (GTK3)

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19053] opened 2021-01-21 16:10 UTC
*Issue migrated from trac ticket # 19053*

**component:** wxGTK | **priority:** normal | **keywords:** wxStaticText GTK3

#### 2021-01-21 16:10:30: Dummy created the issue

___
A `wxStaticText` will appear truncated on wizard pages if it is in bold.

Bold text appears correctly on the first page of the wizard, but is truncated on other pages.
It is a GTK3-specific issue because it is displayed correctly with GTK2.

Please see the attached changes for the wizard sample, to reproduce this issue.

With GTK2, the second wizard page looks correct:

[[Image(wizard_wx314_gtk2.png)]]

With GTK3, the text on the second wizard page is truncated:

[[Image(wizard_wx314_gtk3.png)]]

**Comment by vadz** [comment] 2022-06-16 23:08
Unfortunately I won't have time to do anything about this before 3.2.0, sorry.

**Comment by edward-dauvergne** [comment] 2022-07-25 11:36
I experiences a similar issue [GTK3 Refresh or Layout bug when hiding and showing multiple panels.](https://github.com/wxWidgets/wxWidgets/issues/22668).  It appears as if the bug was fixed with the v3.2.0 tag.

**Comment by taler21** [comment] 2022-07-25 12:50
As mentioned in [this comment](https://github.com/wxWidgets/wxWidgets/issues/19053#issuecomment-1011258108), the changes in commit 3217a4e8a26bf30758c00852738c0612ca931909 improved the misbehavior but didn't completely fix it.

With the following changes to the wizard sample, the issue is still visible, even with wxWidgets-3.2.0.

```patch
diff -r -u -p a/samples/wizard/wizard.cpp b/samples/wizard/wizard.cpp
--- a/samples/wizard/wizard.cpp	2022-07-25 14:03:43.333751200 +0200
+++ b/samples/wizard/wizard.cpp	2022-07-25 14:08:40.302630200 +0200
@@ -249,13 +249,9 @@ public:
 
         wxBoxSizer *mainSizer = new wxBoxSizer(wxVERTICAL);
 
-        mainSizer->Add(
-            new wxStaticText(this, wxID_ANY, "Try checking the box below and\n"
-                                       "then going back and clearing it"),
-            0, // No vertical stretching
-            wxALL,
-            5 // Border width
-        );
+        wxStaticText* text = new wxStaticText(this, wxID_STATIC, _("text_part_1 / text_part_2:"), wxDefaultPosition, wxDefaultSize, 0);
+        text->SetFont( text->GetFont().MakeBold() );
+        mainSizer->Add(text, 0, wxALIGN_LEFT|wxALL, 5);
 
         m_checkbox = new wxCheckBox(this, wxID_ANY, "&Skip the next page");
         mainSizer->Add(
@@ -395,13 +391,24 @@ MyWizard::MyWizard(wxFrame *frame, bool 
 
     // a wizard page may be either an object of predefined class
     m_page1 = new wxWizardPageSimple(this);
+    {
+        wxBoxSizer *mainSizer = new wxBoxSizer(wxVERTICAL);
 
-    /* wxStaticText *text = */ new wxStaticText(m_page1, wxID_ANY,
-             "This wizard doesn't help you\nto do anything at all.\n"
-             "\n"
-             "The next pages will present you\nwith more useless controls.",
-             wxPoint(5,5)
-        );
+        wxStaticText* text = new wxStaticText(m_page1, wxID_STATIC, _("text_part_1 / text_part_2:"), wxDefaultPosition, wxDefaultSize, 0);
+        text->SetFont( text->GetFont().MakeBold() );
+        mainSizer->Add(text, 0, wxALIGN_LEFT|wxALL, 5);
+
+
+        wxSize textSize = wxSize(150, 200);
+        if (((wxFrame*) wxTheApp->GetTopWindow())->GetMenuBar()->IsChecked(Wizard_LargeWizard))
+            textSize = wxSize(150, wxGetClientDisplayRect().GetHeight() - 200);
+
+
+        wxTextCtrl* textCtrl = new wxTextCtrl(m_page1, wxID_ANY, wxEmptyString, wxDefaultPosition, textSize, wxTE_MULTILINE);
+        mainSizer->Add(textCtrl, 0, wxALL|wxEXPAND, 5);
+
+        m_page1->SetSizerAndFit(mainSizer);
+    }
 
     // ... or a derived class
     wxRadioboxPage *page3 = new wxRadioboxPage(this);

```

![wizard-page2_wx320_gtk3](https://user-images.githubusercontent.com/99262969/180780943-20c6b6e7-59fd-414f-98a4-3df1e65fbcaa.png)

**Comment by vadz** [comment] 2022-07-25 13:47
Yes, I know that the bug isn't fixed, but according to Paul, the problem is really in `wxWizard` and we just need to add the missing `Layout()` somewhere. I didn't have time to return to debugging this, so if anybody could do it and find how exactly does `wxWizard` need to be modified, it would be very welcome.

**Comment by vadz** [comment] 2023-10-03 14:34
Actually I think the problem is not just in `wxWizard` but appears whenever you layout a hidden window and then show it. For example I'm running into what I strongly suspect is the same bug in `wxBusyInfo`: if you show the "rich busy info" in the dialog sample, you can see that it doesn't show its text (only title) because it is truncated. This happens because the title uses a bigger font but in `wxBusyInfo::Init()` its height is still the same as if it used a normal font, while showing and actually laying it out later gives it its full height which pushes the text below it beyond the window boundary.

I have no idea how to fix this, no amount of post-factum relayouts can help here, we really need the actual height of the text before it is shown -- but we can't get it. Amazingly, showing the frame before calling `Layout()` helps when running under Wayland but _not_ when using X(Wayland), somehow.

For now I've added a really dirty hack to fix `wxBusyInfo` in #23936, but we really need some better solution.

**Comment by Newbytee** [comment] 2023-10-21 18:14
Yes, this is definitely not just in wxWizard. In the applications we are developing at my workplace, we've been struggling with this issue for a while. We thought it was an issue with our internal wxWidgets wrapper, but today I looked into it and reproduced it without our wrapper, which eventually lead me here. My reproducer was just this (sorry, wxPython):

```python
import wx

class Page(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent)

        text_font = wx.Font()
        text_font.SetPointSize(18)
        text = wx.StaticText(self, -1, "Settings")
        text.SetFont(text_font)


class TextRenderingIssueFrameNoWxw(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, "Hi! This is another title!")

        panel = wx.Panel(self)
        notebook = wx.Notebook(panel)
        page = Page(notebook)
        notebook.AddPage(page, "Main page")

        sizer = wx.BoxSizer()
        sizer.Add(notebook, 1, wx.EXPAND)
        panel.SetSizer(sizer)


def main():
    app = wx.App()
    app_frame = TextRenderingIssueFrameNoWxw()
    app.SetTopWindow(app_frame)
    app_frame.Show(True)

    app.MainLoop()
```

**Comment by imciner2** [comment] 2023-10-21 19:05
> Actually I think the problem is not just in wxWizard but appears whenever you layout a hidden window and then show it.

I'm pretty sure this is the perennial GTK bold text layout issue that we have been playing wack-a-mole with for a while. We originally saw issues with bold text in KiCad years ago (https://gitlab.com/kicad/code/kicad/-/issues/1915) in some custom dialogs just using the static texts. At one point, I thought that @paulcor made some changes that seem to have fixed it (or at least we couldn't see the issue in the dialog originally mentioned when running under a 3.1 version, and when I checked just now on a build with wx 3.2 I don't see bold text cutoff in another location where we had problems). I think the commits that were supposed to have fixed this for the places where ours were broken were https://github.com/wxWidgets/wxWidgets/commit/101c43d0aa703a843f177c449fad73951de199c3 and https://github.com/wxWidgets/wxWidgets/commit/3b4ee5a031b1c2fa29772b90751a82dd7f1d3de0 according to the KiCad ticket, but it has been awhile, so I can't recall if there was anything else.

**Comment by Newbytee** [comment] 2023-10-22 10:01
> > Actually I think the problem is not just in wxWizard but appears whenever you layout a hidden window and then show it.
> 
> I'm pretty sure this is the perennial GTK bold text layout issue that we have been playing wack-a-mole with for a while. We originally saw issues with bold text in KiCad years ago (https://gitlab.com/kicad/code/kicad/-/issues/1915) in some custom dialogs just using the static texts. At one point, I thought that @paulcor made some changes that seem to have fixed it (or at least we couldn't see the issue in the dialog originally mentioned when running under a 3.1 version, and when I checked just now on a build with wx 3.2 I don't see bold text cutoff in another location where we had problems). I think the commits that were supposed to have fixed this for the places where ours were broken were [101c43d](https://github.com/wxWidgets/wxWidgets/commit/101c43d0aa703a843f177c449fad73951de199c3) and [3b4ee5a](https://github.com/wxWidgets/wxWidgets/commit/3b4ee5a031b1c2fa29772b90751a82dd7f1d3de0) according to the KiCad ticket, but it has been awhile, so I can't recall if there was anything else.

Thanks! Looking at the list of tags those commits are included in, it seems like wxWidgets 3.1.1 is the first version. The Ubuntu version I'm using to test this on is using wxWidgets 3.0.5, so maybe that's why I'm still experiencing. Sorry for the false positive.

**Comment by vadz** [comment] 2024-08-20 00:28
This is really, really bad, I just half an hour on another (complicated) layout problem which turned out to be due to the same problem again.

I still have no idea what to do about this, could we perhaps have a hidden (but realized) control used just for measurements?

**Comment by paulcor** [comment] 2024-08-20 16:54
> could we perhaps have a hidden (but realized) control used just for measurements?

Based on [this](https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.43/gtk/gtkwidget.c#L4850), I think the widget has to be visible for style information to be valid.

**Comment by vadz** [comment] 2024-08-20 16:59
Maybe we should replace `wxStaticText` with `wxGenericStaticText` in wxGTK? AFAICS it shouldn't suffer from this problem and it's the static text which is typically made bold/smaller/larger.

In principle, we could even dynamically switch to the generic widget if `SetFont()` is called.

Of course, this

1. Doesn't solve the problem for the other widgets.
2. Is pretty ugly.

But I just don't know what else to do, I can't even come up with the idea of a new API that would work with GTK: we need to know the size of the text in order to lay it out and we need it to lay it out before showing it.

**Comment by vadz** [comment] 2024-08-23 22:42
What about another idea: can we use do the same thing `wxGenericStaticText::DoGetBestClientSize()` does, i.e. just measure the text extent ourselves, in `wxStaticText::DoGetBestSize()` if the font has been changed but the window isn't realized yet?

This still doesn't help with the other widgets, but is less ugly, simpler to implement, and doesn't break accessibility (and GTK Inspector and such).

Unless someone sees why this is obviously a bad idea, I'm going to try to put this in place.

**Comment by vadz** [comment] 2024-08-24 13:13
So it turns out that the original `wxWizard` bug was due to a hack with page visibility and can be fixed by simply removing this (unnecessary) hack entirely, see 7e14fda22c3a25379683e104f339206ca1251d2e. I believe this takes care of this bug itself, at least the last patch above starts working correctly for me with just this commit.

This doesn't solve the rest of the problems due to using the wrong size for `wxStaticText`, however, so I've also pushed 10e3c58def552e2b997a87cd41dcbfbf84b9de79 which is more problematic but does fix those of them that I ran into.

If anybody wants to test it, the following patch can be useful to see when our method returns or would return different values from GTK ones.

<details>
<summary>Patch for debugging</summary>

```diff
diff --git a/src/gtk/stattext.cpp b/src/gtk/stattext.cpp
index 7e44a7ab29..8d43402526 100644
--- a/src/gtk/stattext.cpp
+++ b/src/gtk/stattext.cpp
@@ -239,6 +239,7 @@ wxSize wxStaticText::DoGetBestSize() const
     // Do not return any arbitrary default value...
     wxASSERT_MSG( m_widget, wxT("wxStaticText::DoGetBestSize called before creation") );
 
+    auto doGet = [this]() {
     wxSize size;
     if ( m_computeOurOwnBestSize )
     {
@@ -295,6 +296,30 @@ wxSize wxStaticText::DoGetBestSize() const
     // Adding 1 to width to workaround GTK sometimes wrapping the text needlessly
     size.x++;
     return size;
+    };
+
+    const wxSize size = doGet();
+    wxString s;
+    if ( m_computeOurOwnBestSize )
+    {
+        wxConstCast(this, wxStaticText)->m_computeOurOwnBestSize = false;
+        const wxSize sizeGTK = doGet();
+        if ( sizeGTK != size )
+            wxLogTrace("size", "%p: best size=(%d, %d), GTK size=(%d, %d)",
+                       this, size.x, size.y, sizeGTK.x, sizeGTK.y);
+        wxConstCast(this, wxStaticText)->m_computeOurOwnBestSize = true;
+    }
+    else
+    {
+        wxConstCast(this, wxStaticText)->m_computeOurOwnBestSize = true;
+        const wxSize sizeOur = doGet();
+        if ( sizeOur != size )
+            wxLogTrace("size", "%p: best size=(%d, %d), our size=(%d, %d)",
+                       this, size.x, size.y, sizeOur.x, sizeOur.y);
+        wxConstCast(this, wxStaticText)->m_computeOurOwnBestSize = false;
+    }
+
+    return size;
 }
 
 bool wxStaticText::GTKWidgetNeedsMnemonic() const
```
</details>

**Closed** 2024-08-25 15:36 UTC
Labels: GTK, confirmed, v3.1.5
