### ISSUE TITLE
MacOS: crash on event loop bad access with Release O2 optimized

### ISSUE THREAD

**Issue by aisnote** [wxWidgets/wxWidgets#22466] opened 2022-05-27 22:52 UTC
**Describe the bug**
Crash with Release O2 compile 

**Expected vs observed behaviour**
Crash as the picture.

**Patch or snippet allowing to reproduce the problem**
see picture, 

Debug is ok.

And Release without optimized also ok.

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.
1. I build wx 3.1.4 as static lib on macos
2. App Release building with O2 optimized, will meet event loop crash issue
![image](https://user-images.githubusercontent.com/1201634/170797975-90aa1e0d-c3d4-4dd1-9076-3178945b4a6c.png)

**Platform and version information**
 - wxWidgets version you use: 3.1.4
 - wxWidgets port you use:  wxOSX
 - OS and its version: MacOS 12.4

**Comment by vadz** [comment] 2022-05-27 23:10
There seems to be a lot of things going on in other threads, so I'm not sure at all that it's a wxWidgets bug. Can you reproduce it in the minimal sample? If not, please try to provide a minimal patch to it reproducing the problem because there is simply nothing we can do about it otherwise.

Also, please check 3.1.6 or the latest master.

**Comment by aisnote** [comment] 2022-05-28 02:03
Will try 3.1.6 to see. 
Disable the optimize, will not has this issue

**Comment by csomor** [comment] 2022-06-11 16:33
I sometimes had incorrect code generation with -O2, could you please try -Os ? but as Vadim said, there are threads possible interfering, since the crash is not happening in wx code but deeper ...

**Comment by aisnote** [comment] 2022-08-11 04:54
Actually I figured out the solution, but still don't know the root cause.
I just removed the lambda capture variable since that one is useless. Maybe it caused o2 optimized. 
Welcome comments and thanks to @csomor and @vadz .

![image](https://user-images.githubusercontent.com/1201634/184066830-16aa90b6-088d-450d-96b3-2db082958979.png)

**Comment by vadz** [comment] 2022-08-11 10:53
Wait, are you capturing a pointer to a local variable? It doesn't seem surprising that it crashes then, this pointer becomes invalid as soon as the function exits, i.e. it's "just" a bug in your code which you've fixed now.

**Closed by vadz** 2022-08-11 10:53 UTC
Labels: macOS, repro needed

**Comment by aisnote** [comment] 2022-08-11 16:12
My purpose is to capture by the reference. Anyway, I knew the root cause now. Thanks.
