### ISSUE TITLE
Endless stream of repaint messages when using `wxStaticBox` with `WS_EX_COMPOSITE`

### ISSUE THREAD

**Issue by turkin60** [wxWidgets/wxWidgets#22982] opened 2022-11-21 03:02 UTC
### Description

The problem occurs when used simultaneously in the same wxDialog/wxFrame wxCollapsiblePane and wxStaticBoxSizer. To reproduce apply the patch to collpane sample

```diff
Index: collpane.cpp
===================================================================
--- collpane.cpp	(revision 142548)
+++ collpane.cpp	(working copy)
@@ -40,6 +40,7 @@
 #include "wx/filepicker.h"
 #include "wx/fontpicker.h"
 #include "wx/aboutdlg.h"
+#include <wx/statbox.h>
 
 #ifndef wxHAS_IMAGES_IN_RESOURCES
     #include "../sample.xpm"
@@ -196,6 +197,9 @@
     menuBar->Append(helpMenu, "&Help");
     SetMenuBar(menuBar);
 
+wxStaticBoxSizer *sb = new wxStaticBoxSizer(new wxStaticBox(this, -1, "Static box"), wxVERTICAL);
+sb->Add(new wxStaticText(sb->GetStaticBox(), -1, "Insise static box"), 0, wxALL, 2);
+
     m_collPane = new wxCollapsiblePane(this, -1, "This is a wxCollapsiblePane");
     wxWindow *win = m_collPane->GetPane();
 
@@ -214,6 +218,7 @@
     m_collHeaderCtrl = new wxCollapsibleHeaderCtrl(this, wxID_ANY, "Collapsed wxCollapsibleHeaderCtrl");
 
     wxSizer* const sizerTop = new wxBoxSizer(wxVERTICAL);
+sizerTop->Add(sb, wxSizerFlags(1).Expand());
     sizerTop->Add(m_collPane, wxSizerFlags(1).Expand());
     sizerTop->Add(m_collHeaderCtrl);
     SetSizer(sizerTop);
```

After starting the frame will be empty, the content will appear only when the frame is moved.

### Platform and version information

- wxWidgets version  you use: 3.3 
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 8.1, Windows 10

+ GTK version: 
+ Which GDK  backend is used:
+ Current theme:

**Comment by vadz** [comment] 2022-11-23 02:35
Thanks for reporting!

I can indeed reproduce the problem, but I don't understand what's going on here: we're getting a never ending stream of `WM_PAINT` messages for the collapsible pane, but I don't know why. Moreover, just moving the code creating the static box below `wxCollapsibleHeaderCtrl` creation avoids the problem, which is even more mysterious.

This is a regression, as the problem is related to using `WS_EX_COMPOSITED` and disappears when `wx_msw_window_no_composited=1` is set in the environment, so it's important to fix it but right now I really have no idea what's going on here.

**Comment by vadz** [comment] 2022-11-27 18:21
Also note that this is not specific to `wxCollapsiblePane` but can be reproduced by just adding
```cpp
    wxSizer* st = new wxBoxSizer(wxVERTICAL);
    st->Add(new wxStaticBox(this, wxID_ANY, "Box"));
    st->Add(new wxWindow(this, wxID_ANY));
    SetSizer(st);
```
to the frame ctor of any sample (e.g. the minimal one).

And `wxStaticBox` is probably nothing special neither, `WS_EX_TRANSPARENT` is the real culprit here, although I don't understand why is it only a problem when adding the windows in the order above but _not_ when adding the static box second. So this bug can also be fixed by removing `WS_EX_TRANSPARENT` style, i.e. reverting 616586f301 (Remove wxStaticBox custom drawing code entirely, 2022-11-08) but that's not really great neither.

**Comment by vadz** [comment] 2022-11-28 16:32
I can avoid the endless stream of `WM_PAINT`s by forcibly validating the region, i.e. doing this
```diff
diff --git a/src/msw/window.cpp b/src/msw/window.cpp
index e9a6221414..4c9b11e5ce 100644
--- a/src/msw/window.cpp
+++ b/src/msw/window.cpp
@@ -5391,22 +5391,56 @@ bool wxWindowMSW::HandlePaint()
     wxNcPaintEvent eventNc(this);
     HandleWindowEvent(eventNc);
 
-    // don't keep an HRGN we don't need any longer (GetUpdateRegion() can only
-    // be called from inside the event handlers called above)
-    m_updateRegion.Clear();
-
     wxPaintDCImpl::EndPaint((wxWindow *)this);
 
     paintStack.pop();
 
-    // It doesn't matter whether the event was actually processed or not here,
-    // what matters is whether we already painted, and hence validated, the
-    // window or not. If we did, either the event was processed or we called
-    // OnPaint() above, so we should return true. If we did not, even the event
-    // was processed, we must still call MSWDefWindowProc() to ensure that the
-    // window is validated, i.e. to avoid the problem described in the comment
-    // before paintStack definition above.
-    return createdPaintDC;
+    if ( !createdPaintDC )
+    {
+        // Even if the event handler processed the event but didn't create a
+        // wxPaintDC, we still must create it ourselves in order to validate
+        // the update region. But instead of doing this directly, delegate to
+        // the default window proc as it might do something more than we do.
+        MSWDefWindowProc(WM_PAINT, 0, 0);
+    }
+
+    // By now, we really shouldn't have any damaged region any more but,
+    // somehow, when using a window with WS_EX_TRANSPARENT style inside a
+    // window with WS_EX_COMPOSITED, we can still have it (and it doesn't
+    // matter if we called BeginPaint() directly or did it via DefWindowProc).
+    //
+    // Revalidate it explicitly in this case, as while this is ugly, it's
+    // better than getting stuck in an endless loop of WM_PAINT messages.
+    // Note that the window still might be (won't be?) repainted correctly as
+    // it we can't paint anything on it in this state, so it's really just a
+    // last resort solution to at least prevent the program from endlessly
+    // eating CPU, see #22982.
+    switch ( ::GetUpdateRgn(GetHwnd(), hRegion, FALSE) )
+    {
+        case ERROR:
+            wxLogLastError(wxT("GetUpdateRgn"));
+            break;
+
+        case NULLREGION:
+            break;
+
+        default:
+            if ( ::ValidateRect(GetHwnd(), nullptr) )
+            {
+                wxLogLastError(wxT("ValidateRect"));
+                break;
+            }
+            break;
+    }
+
+    // don't keep an HRGN we don't need any longer (GetUpdateRegion() can only
+    // be called from inside the event handlers called above)
+    m_updateRegion.Clear();
+
+    // As we either painted the window ourselves or already called default
+    // window proc to do it for us, the message is effectively processed
+    // whether the wx event was processed or not.
+    return true;
 }
 
 // Can be called from an application's OnPaint handler
```
but, as expected, the window then just remains unpainted, so I'm not going to commit this, but it really looks like `WS_EX_COMPOSITED` is just not compatible with `WS_EX_TRANSPARENT` -- and I can even reproduce this in the minimal example using Win32 API directly, so it's not due to anything wx does.

**Closed** 2022-12-04 01:49 UTC
Labels: MSW, regression
