### ISSUE TITLE
AUI notebook page appears blank after another page closed (in split mode)

### ISSUE THREAD

**Issue by ColinTebbutt** [wxWidgets/wxWidgets#24063] opened 2023-11-15 14:55 UTC
I've discovered a problem where an AUI notebook page appears blank after another page closed (in split mode). The notebook pages here are based on wxStyledTextCtrl.

To reproduce, do the following:
- split the AUI notebook so that it contains two sections, with one or more pages on the left half, and two pages on the right.
- select the rightmost page in the right half (script2 in the image).
- select a page on the left half (script3 in the image).
![before](https://github.com/wxWidgets/wxWidgets/assets/60915614/c6d810ca-a110-4f2d-948e-81e29ba42983)

- click on the close botton of the rightmost page in the right half. Notice that script1 is incorrectly shown as a blank page.
![after](https://github.com/wxWidgets/wxWidgets/assets/60915614/120f0646-86fc-427a-81a0-ce1df659b4d8)

The page contents can be restored by clicking on the affected tab (script1 in the image).
![expected](https://github.com/wxWidgets/wxWidgets/assets/60915614/71e0a45b-5a8e-4b72-bebb-2ed9bb730260)

It would be helpful if anyone can suggest a work-around.

**Comment by fcloud2020** [comment] 2023-11-19 13:10
I can't reproduce this problem. What is your development evironment?

**Comment by ColinTebbutt** [comment] 2023-11-20 06:02
It's Windows 10

**Comment by fcloud2020** [comment] 2023-11-20 14:28
I can reproduce it now. This problem may be ralated to the miscalculation of the wxAuiNoteBook's index. Because this only happens when we drag a page and split the screen.

**Comment by vadz** [comment] 2023-12-24 02:10
@ColinTebbutt Could you please check if you still see the problem (or any other problems) with #24160? TIA!

**Comment by fcloud2020** [comment] 2024-01-02 00:44
This problem can be fixed by commenting out the two lines marked.
I think this problem is caused by the fact that the page is not refreshed immediately although it is set to activate.

![issue_24063](https://github.com/wxWidgets/wxWidgets/assets/70119079/f83d5f16-fe1b-4723-88ab-afabad499ac8)

**Comment by fcloud2020** [comment] 2024-01-02 01:50
> @ColinTebbutt Could you please check if you still see the problem (or any other problems) with #24160? TIA!

**Yes**，it's still here with #24160.

**Comment by vadz** [comment] 2024-01-03 18:08
Thanks for testing this and for proposing a fix, but I don't think it's quite correct, even if it works around the problem: closing the page in one split shouldn't change the global notebook selection IMO. So I've created #24184 with the alternative fix, please let me know if you see any problems with it. TIA!

**Comment by fcloud2020** [comment] 2024-01-07 04:52
@vadz It's great! 
But I found another problem. Please look at this GIF.

![20240107-122917](https://github.com/wxWidgets/wxWidgets/assets/70119079/b282091b-e9fe-4918-a12f-33a3121ea771)

After closed all pages in the first pane, the current page will jump to the first page in the second pane.

**Comment by fcloud2020** [comment] 2024-01-07 05:03
I tried to fix this problem by changing the code. As shown below.

![issue_24063_2](https://github.com/wxWidgets/wxWidgets/assets/70119079/871d45a1-32c7-4e3a-95db-c0cb2e7588a3)

But it only works for the second pane, the third pane doesn't work.

**Comment by ColinTebbutt** [comment] 2024-01-09 08:58
Hi! Sorry for the late reply - I've been away for a while. The changes in #24184 solve the (original) problem for my application - thanks.

**Closed** 2024-01-10 17:45 UTC
Labels: AUI
