### ISSUE TITLE
wxPropertyGrid + Hide/Unhide item results in drawing errors and crashes

### ISSUE THREAD

**Issue by roenck** [wxWidgets/wxWidgets#22428] opened 2022-05-15 21:55 UTC
**Describe the bug**
If a property-grid contains a wxEnumProperty (e.q. values hide + unhide) and following other properties that are hidden or shown by this enum-property and the scroll-area is moved to the last possible position before, than a hide of just 1 property results in the enum-property is drawn at wrong position. And also the application crash some time later (sometimes), because of detached property.

**Expected vs observed behaviour**
No painting errors, no crashes when porperties hidden and shown again.

**Patch or snippet allowing to reproduce the problem**

![1](https://user-images.githubusercontent.com/100382302/168495077-4e23e966-123f-4ae9-8c1c-928e85333cbe.png)
![2](https://user-images.githubusercontent.com/100382302/168495080-ab4a7f22-c77c-479f-b8b5-24088d2337da.png)
![3](https://user-images.githubusercontent.com/100382302/168495082-019d70c7-5244-40bb-adc8-4f228795e1b4.png)
![4](https://user-images.githubusercontent.com/100382302/168495780-1449b57f-f79d-450a-854f-3bfe505b2c93.png)

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.
1. Ceate an application that uses wxAuiManager
2. Create a wxPropertyGrid and put it in a frame of aui
3. Add properties before
4. Add a enum-property that enabled hide/unhide the next property
5. Add some properties after that
6. start application and ensure the window-size of the wxAui-Frame is to small to show everything
7. scroll down until last possible position
8. click on the enum-property and select a value that hide a property after the enum-property
9. the enum-property is drawn at wrong position and the app crashes some time

**Platform and version information**
 - wxWidgets version you use: 3.1.5 and 
 latest commit 6268b5c619ac7bd7479c0912275bce89d67d1f23 (HEAD -> master, origin/master, origin/HEAD)

 - wxWidgets port you use: wxGTK (can't reproduce it with MSW)
 - OS and its version: Ubuntu 20.04
 - For wxGTK only:
   + GTK version: 3.24.20
   + Which GDK backend is used: X11

**Comment by a-wi** [comment] 2022-05-17 21:01
I cannot reproduce this issue with below sample app. On Ubuntu 20.04 (GTK 3.24.20) and Debian 11 (GTK 3.24.24) wxEnumProperty is positioned as expected and there are no crashes.
Could you check if it works for you?

```
#include <wx/wx.h>
#include <wx/aui/aui.h>
#include <wx/propgrid/propgrid.h>
#include <wx/propgrid/manager.h>

class FormMain : public wxFrame
{
public:
    FormMain();
    ~FormMain();

private:
    wxAuiManager m_auiManager;
};

class cxApplication : public wxApp
{
public:

    virtual bool OnInit() wxOVERRIDE
    {
        FormMain* frame = new FormMain();
        frame->Show(true);
        return true;
    }
};

wxIMPLEMENT_APP(cxApplication);

FormMain::FormMain() : wxFrame(NULL, wxID_ANY, "Sample", wxDefaultPosition, wxSize(600, 400))
{
    m_auiManager.SetManagedWindow(this);

    wxPropertyGridManager* pgman = new wxPropertyGridManager(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxPG_TOOLTIPS | wxPG_TOOLBAR);
    wxPropertyGridPage* pg = pgman->AddPage("Page");

    for (int i = 0; i < 9; i++)
    {
        pg->Append(new wxIntProperty(wxString::Format("Property %d", i), wxPG_LABEL, i));
    }

    wxPGChoices sel;
    sel.Add("Item 1", 10);
    sel.Add("Item 2", 20);
    sel.Add("Item 3", 30);
    sel.Add("Item 4", 40);
    sel.Add("Item 5", 50);
    pg->Append(new wxEnumProperty("EnumProperty", wxPG_LABEL, sel, 10));

    for (int i = 9; i < 15; i++)
    {
        pg->Append(new wxIntProperty(wxString::Format("Property %d", i), wxPG_LABEL, i));
    }

    m_auiManager.AddPane(pgman, wxAuiPaneInfo().Center().Caption("Property Grid").
            CloseButton(false).MinSize(wxSize(200,200)));
    m_auiManager.Update();
}

FormMain::~FormMain()
{
}
```

**Comment by roenck** [comment] 2022-05-17 22:37
Maybe a combination of some things (e.q.: windows-size, status-bar enabled, clear-call on page-properties before).

Here is a test application that contains the buggy behaviour:

[PropGridBug.zip](https://github.com/wxWidgets/wxWidgets/files/8711932/PropGridBug.zip)

Here a video, what happens:

![PropGridBug](https://user-images.githubusercontent.com/100382302/168922588-7a824f6a-6a21-47b9-a85e-806f292193af.gif)


OffTopic:
Seems like, there is also some other bug with a message  "Cannot obtain display info for detached property"(https://forums.wxwidgets.org/viewtopic.php?f=1&t=49258). Don't know what this is, it happens seldom, but kills the app. In my opinion some synchronization issue, but can't reproduce this and it's very problematical. But maybe the same origin.

**Comment by a-wi** [comment] 2022-05-18 17:53
I cannot reproduce the issue with your code - positioning is OK, no crashes.
BTW, you call in your sample code wxPropertyGridPageState::DoClear() method but wxPropertyGridPageState [documentation](https://docs.wxwidgets.org/trunk/classwx_property_grid_page_state.html) says `Generally you should not use this class directly, but instead member functions in wxPropertyGridInterface, wxPropertyGrid, wxPropertyGridPage, and wxPropertyGridManager.`
So, you should call wxPropertyGridPage::Clear() instead.
Please also note that `DoSomething()` methods are generally for internal purposes only and they are publicly exposed only due to the technical reasons.

**Comment by roenck** [comment] 2022-05-19 11:55
- Don't get any messages onto console.
- changed DoClear into Clear, bug still there and exists.

DoSomething(): don't know this, thanks for the hint, but in my opinion not very meaningful to make such things public and if not possible otherwise to name such things for example 'Internal' (or somehing equivalent) that is visible to none-widget developer without reading the whole manual.

**Comment by roenck** [comment] 2022-05-19 11:55
How can I support you to find/fix the bug?

**Comment by a-wi** [comment] 2022-05-21 20:58
Eventually I've managed to reproduce the issue with positioning - thanks for the hints.
Please check with current master if it's fixed now.

**Closed** 2022-05-27 17:14 UTC
